const fs = require('fs');

const page = [
"'use client';",
"import { useState, useEffect, useRef, memo, useCallback, useMemo } from 'react';",
"import dynamic from 'next/dynamic';",
"import GalleryView from './components/GalleryView';",
"",
"const LockerRoomScene = dynamic(() => import('./components/LockerRoom'), { ssr: false });",
"",
"const RARITY_GLOW: Record<string,string> = {",
"  common:'0 0 16px 5px rgba(220,220,255,0.45)',",
"  limited:'0 0 22px 7px rgba(234,179,8,0.75)',",
"  rare:'0 0 26px 8px rgba(59,130,246,0.85)',",
"  super_rare:'0 0 30px 10px rgba(239,68,68,0.9)',",
"  unique:'0 0 36px 12px rgba(168,85,247,0.95)',",
"};",
"const RARITY_COLOR: Record<string,string> = {",
"  common:'#9ca3af',limited:'#eab308',rare:'#3b82f6',super_rare:'#ef4444',unique:'#a855f7',",
"};",
"const RARITY_FILL: Record<string,string> = {",
"  common:'#a8a8b5',limited:'#b48a14',rare:'#1e4ba8',super_rare:'#a82a2a',unique:'#7e3fc4',",
"};",
"const RARITY_ORDER: Record<string,number> = { unique:0, super_rare:1, rare:2, limited:3, common:4 };",
"const HOF_KEY = '__HOF__';",
"",
"// Labels lisibles pour les editions speciales",
"const SPECIAL_LABELS: Record<string,string> = {",
"  stellar_shiny_base:'Shiny', stellar_holo_base:'Holo', stellar_meteor_base:'Meteor',",
"  stellar_shiny_jersey_number:'Shiny Jersey', stellar_holo_jersey_number:'Holo Jersey',",
"  stellar_standard_base:'Standard', playoffs:'Playoffs', showtime:'Showtime', sunset:'Sunset',",
"};",
"const specialLabel=(v:string)=>SPECIAL_LABELS[v]||v;",
"const STANDARD_SET=new Set(['stellar_standard_base']);",
"const isSpecialCard=(c:any)=>{ const se=c.specialEdition; if(!se)return false; if(STANDARD_SET.has(se))return false; return true; };",
"const playerKey=(c:any)=>(c.anyPlayer?.lastName||c.slug.split('-')[0])+'|'+(c.anyPlayer?.shirtNumber??'');",
"const dedupeByPlayer=(list:any[])=>{",
"  const better=(a:any,b:any)=>{ const sa=isSpecialCard(a)?1:0, sb=isSpecialCard(b)?1:0; if(sa!==sb) return sa>sb?a:b; return (a.xp??0)>=(b.xp??0)?a:b; };",
"  const byPlayer:Record<string,any>={};",
"  for(const c of list){ const k=playerKey(c); byPlayer[k]=byPlayer[k]?better(byPlayer[k],c):c; }",
"  return Object.values(byPlayer);",
"};",
"",
"const isNBA=(slug:string)=>/\\d{8}/.test(slug);",
"const parseCard=(name:string)=>{",
"  const parts=name.split('\u2022');const left=parts[0].trim();const right=(parts[1]||'').trim();",
"  const sm=left.match(/(\\d{4}-\\d{2})/);const season=sm?sm[1]:'';",
"  const pn=left.replace(/\\d{4}-\\d{2}/,'').trim();",
"  const ln=pn.split(' ').pop()!.toUpperCase();",
"  const sr=right.match(/(\\d+\\/\\d+)/);",
"  return {playerName:pn,lastName:ln,season,serial:sr?sr[1]:null};",
"};",
"const nameFontSize=(l:number)=>l<=5?'2rem':l<=7?'1.65rem':l<=9?'1.35rem':l<=11?'1.1rem':'0.9rem';",
"",
"const CardBack=memo(({ card }: { card: any }) => {",
"  const { season, serial } = parseCard(card.name);",
"  const rc = RARITY_COLOR[card.rarityTyped]||'#9ca3af';",
"  const lastName=(card.anyPlayer?.lastName||parseCard(card.name).lastName).toUpperCase();",
"  const shirtNumber=card.anyPlayer?.shirtNumber??null;",
"  return(",
"    <div style={{position:'absolute',top:0,left:0,right:0,bottom:0,backfaceVisibility:'hidden',transform:'rotateY(180deg)',borderRadius:'0.4rem',overflow:'hidden',background:'radial-gradient(ellipse at center,#15151f,#07070d)',display:'flex',flexDirection:'column',borderTop:'3px solid '+rc,borderBottom:'3px solid '+rc}}>",
"      <div style={{padding:'0.5rem',borderBottom:'1px solid rgba(255,255,255,0.06)',textAlign:'center'}}>",
"        <p style={{margin:0,fontSize:'0.75rem',color:rc,fontWeight:800,letterSpacing:'0.06em'}}>myNFTlocker</p>",
"        <p style={{margin:'2px 0 0',fontSize:'0.6rem',color:'#b8956a',fontWeight:600}}>{isNBA(card.slug)?'NBA':'FOOTBALL'} \u2022 {card.seasonYear||season}</p>",
"      </div>",
"      <div style={{padding:'0.4rem',textAlign:'center'}}>",
"        <p style={{margin:0,fontSize:nameFontSize(lastName.length),fontWeight:900,color:'#fff',lineHeight:1.1,textShadow:'0 0 18px '+rc+'99'}}>{lastName}</p>",
"        {shirtNumber!==null&&<p style={{margin:'0.25rem 0 0',fontSize:'1.1rem',color:rc,fontWeight:900}}>#{shirtNumber}</p>}",
"        {serial&&<p style={{margin:'0.1rem 0 0',fontSize:'0.65rem',color:'#b8956a',fontWeight:600}}>{serial}</p>}",
"        {isSpecialCard(card)&&<p style={{margin:'0.15rem 0 0',fontSize:'0.55rem',color:rc,fontWeight:700,letterSpacing:'0.05em'}}>{specialLabel(card.specialEdition)}</p>}",
"      </div>",
"      <div style={{flex:1,display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center'}}>",
"        <p style={{margin:0,fontSize:'1.5rem',fontWeight:800,color:'#fff'}}>{card.averageScore??'--'}</p>",
"        <p style={{margin:0,fontSize:'0.55rem',color:'#d4af37',letterSpacing:'0.2em',textTransform:'uppercase',fontWeight:700}}>L10</p>",
"      </div>",
"      <div style={{padding:'0.3rem',borderTop:'1px solid rgba(255,255,255,0.06)'}}>",
"        <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:'0.15rem'}}>",
"          {[['BEAT L10','--'],['BONUS',card.power?('+'+Math.round((parseFloat(card.power)-1)*100)+'%'):'--'],['GW','--'],['REW','--']].map(([l,v])=>(",
"            <div key={l} style={{textAlign:'center'}}>",
"              <p style={{margin:0,fontSize:'0.92rem',fontWeight:900,color:'#ffffff'}}>{v}</p>",
"              <p style={{margin:'1px 0 0',fontSize:'0.5rem',color:'#e8c456',letterSpacing:'0.06em',textTransform:'uppercase',fontWeight:800}}>{l}</p>",
"            </div>",
"          ))}",
"        </div>",
"      </div>",
"      <div style={{padding:'0.3rem 0.5rem 0.45rem',display:'flex',justifyContent:'center',gap:'0.4rem'}}>",
"        <span style={{padding:'0.15rem 0.5rem',borderRadius:'999px',border:'1px solid '+rc+'66',background:'#000a',fontSize:'0.55rem',fontWeight:800,color:rc}}>BONUS --</span>",
"        <span style={{padding:'0.15rem 0.5rem',borderRadius:'999px',border:'1px solid '+rc+'66',background:rc+'15',fontSize:'0.55rem',fontWeight:700,color:rc,textTransform:'uppercase'}}>{card.rarityTyped.replace('_',' ')}</span>",
"      </div>",
"    </div>",
"  );",
"});",
"CardBack.displayName='CardBack';",
"",
"const LockerSlot=memo(({card,isFlipped,isStarred,isHof,onFlip,onStar}:any)=>{",
"  const [hover,setHover]=useState(false);",
"  const {lastName}=parseCard(card.name);",
"  const dn=(card.anyPlayer?.lastName||lastName).toUpperCase();",
"  const rc=RARITY_COLOR[card.rarityTyped]||'#9ca3af';",
"  const glow=RARITY_GLOW[card.rarityTyped]||RARITY_GLOW.common;",
"  const fill=RARITY_FILL[card.rarityTyped]||RARITY_FILL.common;",
"  const bonus=card.power?('+'+Math.round((parseFloat(card.power)-1)*100)+'%'):null;",
"  const score=card.averageScore!=null?String(card.averageScore):null;",
"  return(",
"    <div style={{display:'flex',flexDirection:'column',borderRadius:'0.65rem',overflow:'hidden',background:'rgba(255,255,255,0.04)',backdropFilter:'blur(8px)',WebkitBackdropFilter:'blur(8px)',border:'1px solid '+rc+'30',boxShadow:(hover?glow+', ':'')+'0 4px 18px rgba(0,0,0,0.5)',transition:'box-shadow 0.3s,transform 0.3s ease',transform:hover?'perspective(800px) rotateY(4deg) rotateX(-2deg) translateY(-5px) scale(1.02)':' perspective(800px) rotateY(0deg) rotateX(0deg) scale(1)',cursor:'pointer'}} onClick={()=>onFlip(card.slug)} onMouseEnter={()=>setHover(true)} onMouseLeave={()=>setHover(false)}>",
"      <div style={{padding:'6px',position:'relative'}}>",
"        <div style={{position:'relative',transformStyle:'preserve-3d',transition:'transform 0.45s ease',transform:isFlipped?'rotateY(180deg)':' rotateY(0deg)',boxShadow:glow,borderRadius:'0.4rem',background:fill}}>",
"          <div style={{backfaceVisibility:'hidden',borderRadius:'0.4rem',overflow:'hidden',position:'relative'}}>",
"            <button style={{position:'absolute',top:'5px',right:'5px',background:isStarred?'#7c3aedcc':'#00000099',border:'none',borderRadius:'50%',width:'24px',height:'24px',cursor:'pointer',fontSize:'12px',display:'flex',alignItems:'center',justifyContent:'center',zIndex:10,opacity:(hover||isStarred)?1:0,transition:'opacity 0.2s',pointerEvents:(hover||isStarred)?'auto':'none'}} onClick={e=>{e.stopPropagation();onStar(card.slug);}}>",
"              {isStarred?'\u2B50':'\u2606'}",
"            </button>",
"            <img src={card.pictureUrl} alt={card.name} loading='lazy' style={{width:'100%',height:'auto',display:'block'}}/>",
"            {hover&&!isFlipped&&(",
"              <div style={{position:'absolute',bottom:0,left:0,right:0,padding:'0.35rem 0.5rem',background:'linear-gradient(to top,rgba(0,0,0,0.92) 0%,rgba(0,0,0,0.55) 65%,transparent 100%)'}}>",
"                <div style={{display:'flex',alignItems:'baseline',gap:'0.3rem'}}>",
"                  <span style={{fontSize:'1.25rem',fontWeight:900,color:'#fff',fontFamily:'monospace',lineHeight:1}}>{score||'\u2014'}</span>",
"                  <span style={{fontSize:'0.48rem',color:rc,fontWeight:800,letterSpacing:'0.14em',textTransform:'uppercase'}}>L10</span>",
"                  {bonus&&<span style={{marginLeft:'auto',fontSize:'0.48rem',color:rc,fontWeight:800,letterSpacing:'0.06em',border:'1px solid '+rc+'55',padding:'0.05rem 0.25rem',borderRadius:'0.2rem'}}>BONUS {bonus}</span>}",
"                </div>",
"                <p style={{margin:'1px 0 0',fontSize:'0.42rem',color:'rgba(255,255,255,0.5)',fontWeight:600,textTransform:'uppercase',letterSpacing:'0.12em',fontFamily:'monospace'}}>{card.rarityTyped.replace('_',' ')} \u2022 {card.anyTeam?.name||''}</p>",
"              </div>",
"            )}",
"          </div>",
"          <CardBack card={card}/>",
"        </div>",
"      </div>",
"      <div style={{padding:'3px 8px 6px',textAlign:'center',borderTop:'1px solid '+rc+'22',background:'rgba(0,0,0,0.2)'}}>",
"        <span style={{fontSize:'0.58rem',fontWeight:800,color:rc,letterSpacing:'0.12em',textTransform:'uppercase',fontFamily:'monospace',textShadow:'0 0 8px '+rc+'66'}}>{dn}</span>",
"      </div>",
"    </div>",
"  );",
"});",
"LockerSlot.displayName='LockerSlot';",
"",
"const FilterMenu=({title,options,current,onSelect}:any)=>{",
"  const [open,setOpen]=useState(false);",
"  const [pos,setPos]=useState({left:0,top:0,maxH:320});",
"  const ref=useRef<HTMLDivElement>(null);",
"  const cur=options.find((o:any)=>o.value===current);",
"  const enter=()=>{const el=ref.current;if(el){const r=el.getBoundingClientRect();const need=options.length*36+14;const avail=window.innerHeight-16;const h=Math.min(need,avail);const top=Math.max(8,Math.min(r.top,window.innerHeight-h-8));setPos({left:r.right,top,maxH:h});}setOpen(true);};",
"  return(",
"    <div ref={ref} style={{position:'relative',marginBottom:'0.15rem'}} onMouseEnter={enter} onMouseLeave={()=>setOpen(false)}>",
"      {/* Declencheur pleine largeur : reste sombre, fine ligne au survol */}",
"      <div style={{width:'100%',padding:'0.35rem 0.5rem',borderRadius:'0.15rem',background:open?'rgba(111,195,232,0.08)':'transparent',borderLeft:open?'2px solid #6fc3e8':'2px solid transparent',cursor:'default',transition:'all 0.12s'}}>",
"        <p style={{fontSize:'0.64rem',fontWeight:800,letterSpacing:'0.14em',textTransform:'uppercase',color:'#eaf2ff',margin:'0 0 0.05rem',opacity:1}}>{title}</p>",
"        <p style={{fontSize:'0.8rem',fontWeight:500,color:open?'#6fc3e8':'#ffffff',opacity:open?1:0.6,margin:0,transition:'all 0.12s',display:'flex',alignItems:'center',justifyContent:'space-between'}}>{cur?cur.label:'\u2014'} <span style={{fontSize:'0.7rem',opacity:0.7}}>\u203A</span></p>",
"      </div>",
"      {open&&(",
"        <div className='thin-sb' style={{position:'fixed',left:pos.left+'px',top:pos.top+'px',maxHeight:pos.maxH+'px',overflowY:'auto',minWidth:'190px',background:'#080a0e',border:'1px solid #6fc3e8',borderRadius:'0.4rem',padding:'0.3rem',boxShadow:'0 14px 38px rgba(0,0,0,0.7),0 0 14px rgba(111,195,232,0.18)',zIndex:300}}>",
"            {options.map((o:any)=>(",
"              <button key={o.value} onClick={()=>onSelect(o.value)} style={{display:'block',width:'100%',textAlign:'left',padding:'0.4rem 0.7rem',borderRadius:'0.25rem',border:'none',borderLeft:o.value===current?'2px solid #f5d76e':'2px solid transparent',cursor:'pointer',fontSize:'0.8rem',fontWeight:o.value===current?700:500,background:o.value===current?'rgba(245,215,110,0.12)':'transparent',color:o.value===current?'#f5d76e':'#cfd8e6',transition:'background 0.1s'}} onMouseEnter={e=>{if(o.value!==current)(e.currentTarget as HTMLElement).style.background='rgba(111,195,232,0.12)';}} onMouseLeave={e=>{if(o.value!==current)(e.currentTarget as HTMLElement).style.background='transparent';}}>{o.label}</button>",
"            ))}",
"        </div>",
"      )}",
"    </div>",
"  );",
"};",

"const NBA_CONF:Record<string,string>={" ,
"  'Atlanta Hawks':'Est','Boston Celtics':'Est','Brooklyn Nets':'Est','Charlotte Hornets':'Est',",
"  'Chicago Bulls':'Est','Cleveland Cavaliers':'Est','Detroit Pistons':'Est','Indiana Pacers':'Est',",
"  'Miami Heat':'Est','Milwaukee Bucks':'Est','New York Knicks':'Est','Orlando Magic':'Est',",
"  'Philadelphia 76ers':'Est','Toronto Raptors':'Est','Washington Wizards':'Est',",
"  'Dallas Mavericks':'Ouest','Denver Nuggets':'Ouest','Golden State Warriors':'Ouest',",
"  'Houston Rockets':'Ouest','Los Angeles Clippers':'Ouest','Los Angeles Lakers':'Ouest',",
"  'Memphis Grizzlies':'Ouest','Minnesota Timberwolves':'Ouest','New Orleans Pelicans':'Ouest',",
"  'Oklahoma City Thunder':'Ouest','Phoenix Suns':'Ouest','Portland Trail Blazers':'Ouest',",
"  'Sacramento Kings':'Ouest','San Antonio Spurs':'Ouest','Utah Jazz':'Ouest',",
"};",
"export default function Home() {",
"  const [slug, setSlug] = useState('');",
"  const [acctOpen, setAcctOpen] = useState(false);",
"  const [cards, setCards] = useState<any[]>([]);",
"  const [hof, setHof] = useState<string[]>([]);",
"  const [flippedSlug, setFlippedSlug] = useState<string|null>(null);",
"  const [loading, setLoading] = useState(false);",
"  const [error, setError] = useState('');",
"  const [mode, setMode] = useState<'locker'|'gallery'>('locker');",
"  const [lockerStart, setLockerStart] = useState(0);",
"  const [teamApi, setTeamApi] = useState('');",
"  // Filtres partages",
"  const [fRarity, setFRarity] = useState('all');",
"  const [fSeason, setFSeason] = useState('all');",
"  const [fSpecial, setFSpecial] = useState('all');",
"  const [fPlayer, setFPlayer] = useState('');",
"  // Galerie",
"  const [gSport,setGSport]=useState('nba');",
"  const [gConf,setGConf]=useState('all');",
"  const [gTeamCustom,setGTeamCustom]=useState('all');",
"  const [gSort,setGSort]=useState('default');",
"  const [gDropOpen,setGDropOpen]=useState(false);",

"  const [lockerSort, setLockerSort] = useState<'majeur'|'collection'|'manual'>('majeur');",
"  const [lineup, setLineup] = useState<Record<string,string[]>>({});",
"  const [defaultTeam, setDefaultTeam] = useState('');",
"",
"  useEffect(() => {",
"    const saved=localStorage.getItem('mynftlocker_hof')||localStorage.getItem('myNFTlocker_hof');",
"    if(saved){setHof(JSON.parse(saved));localStorage.setItem('mynftlocker_hof',saved);}",
"  }, []);",
"",
"  // Premier accEs : pre-remplir le HoF avec les 5 meilleurs L10 (sans doublon)",
"  useEffect(()=>{",
"    if(cards.length===0) return;",
"    if(localStorage.getItem('mynftlocker_hof_init')) return;",
"    const savedHof=localStorage.getItem('mynftlocker_hof');",
"    if(savedHof && JSON.parse(savedHof).length>0){ localStorage.setItem('mynftlocker_hof_init','done'); return; }",
"    const nba=cards.filter(c=>isNBA(c.slug));",
"    const top5=dedupeByPlayer(nba).sort((a:any,b:any)=>(b.averageScore??-1)-(a.averageScore??-1)).slice(0,5).map((c:any)=>c.slug);",
"    setHof(top5);",
"    localStorage.setItem('mynftlocker_hof',JSON.stringify(top5));",
"    localStorage.setItem('mynftlocker_hof_init','done');",
"    if(!localStorage.getItem('mynftlocker_default_team')) setTeamApi(HOF_KEY);",
"  },[cards]);",
"",
"  const handleStar=useCallback((s:string)=>{setHof(prev=>{const next=prev.includes(s)?prev.filter(x=>x!==s):[...prev,s];localStorage.setItem('mynftlocker_hof',JSON.stringify(next));return next;});},[]);",
"  const handleFlip=useCallback((s:string)=>{setFlippedSlug(f=>f===s?null:s);},[]);",
"  const handlePrev=useCallback(()=>{setLockerStart(s=>Math.max(0,s-1));setFlippedSlug(null);},[]);",
"  const handleNext=useCallback((tot:number)=>{setLockerStart(s=>Math.min(s+1,Math.max(0,tot-5)));setFlippedSlug(null);},[]);",
"  const handleTeamChange=useCallback((api:string)=>{setTeamApi(api);setLockerStart(0);setFlippedSlug(null);},[]);",
"  useEffect(()=>{ const s=localStorage.getItem('mynftlocker_lineup'); if(s){try{setLineup(JSON.parse(s));}catch{}} },[]);",
"  useEffect(()=>{ setDefaultTeam(localStorage.getItem('mynftlocker_default_team')||''); },[]);",
"  const handleSetDefault=useCallback((api:string)=>{ localStorage.setItem('mynftlocker_default_team',api); setDefaultTeam(api); },[]);",
"  const handlePin=useCallback((team:string,slug:string)=>{",
"    setLineup(prev=>{",
"      const cur=prev[team]||[];",
"      const next=cur.includes(slug)?cur.filter(s=>s!==slug):[...cur,slug].slice(-5);",
"      const obj={...prev,[team]:next};",
"      localStorage.setItem('mynftlocker_lineup',JSON.stringify(obj));",
"      return obj;",
"    });",
"  },[]);",
"",
"  // reset pagination vestiaire quand un filtre change",
"  useEffect(()=>{setLockerStart(0);},[fRarity,fSeason,fSpecial,fPlayer,teamApi,lockerSort,lineup]);",
"",
"  const fetchCards=async()=>{",
"    if(!slug)return;",
"    setLoading(true);setError('');setFlippedSlug(null);setLockerStart(0);",
"    try{",
"      const res=await fetch('/api/cards?slug='+slug);",
"      const data=await res.json();",
"      if(!data.cards){setError('Joueur introuvable');return;}",
"      setCards(data.cards);",
"    }catch{setError('Erreur reseau');}finally{setLoading(false);}",
"  };",
"",
"  // Options dynamiques",
"  const seasonOptions=useMemo(()=>{",
"    const s=new Set<number>();",
"    for(const c of cards){if(c.seasonYear)s.add(c.seasonYear);}",
"    return [...s].sort((a,b)=>b-a);",
"  },[cards]);",
"  const specialOptions=useMemo(()=>{",
"    const s=new Set<string>();",
"    for(const c of cards){if(isSpecialCard(c))s.add(c.specialEdition);}",
"    return [...s].sort();",
"  },[cards]);",
"",
"  // Filtre cumulable applique a n'importe quelle liste",
"  const applyFilters=useCallback((list:any[])=>{",
"    return list.filter(c=>{",
"      if(fRarity!=='all' && c.rarityTyped!==fRarity) return false;",
"      if(fSeason!=='all' && c.seasonYear!==Number(fSeason)) return false;",
"      if(fSpecial==='standard' && isSpecialCard(c)) return false;",
"      if(fSpecial==='special' && !isSpecialCard(c)) return false;",
"      if(fSpecial!=='all'&&fSpecial!=='standard'&&fSpecial!=='special' && c.specialEdition!==fSpecial) return false;",
"      if(fPlayer){",
"        const ln=(c.anyPlayer?.lastName||'').toLowerCase();",
"        if(!ln.includes(fPlayer.toLowerCase()) && !c.name.toLowerCase().includes(fPlayer.toLowerCase())) return false;",
"      }",
"      return true;",
"    });",
"  },[fRarity,fSeason,fSpecial,fPlayer]);",
"",
"  // Liste equipes : ordre alphabetique par ville + Hall of Fame en tete",
"  const teamList=useMemo(()=>{",
"    const counts:Record<string,number>={};",
"    for(const c of cards){if(isNBA(c.slug)&&c.anyTeam?.name){counts[c.anyTeam.name]=(counts[c.anyTeam.name]||0)+1;}}",
"    const list=Object.entries(counts).map(([api,count])=>({api,display:api,count})).sort((a,b)=>a.api.localeCompare(b.api));",
"    const hofCount=cards.filter(c=>hof.includes(c.slug)).length;",
"    if(hofCount>0) list.unshift({api:HOF_KEY,display:'HALL OF FAME',count:hofCount});",
"    return list;",
"  },[cards,hof]);",
"  useEffect(()=>{ if(teamList.length>0 && !teamList.find(t=>t.api===teamApi)){const pref=localStorage.getItem('mynftlocker_default_team');const target=(pref && teamList.find(t=>t.api===pref))?pref:teamList[0].api;setTeamApi(target);} },[teamList,teamApi]);",
"",
"  // Vestiaire : epingles prioritaires, puis remplissage, puis TOUTES les cartes",
"  const lockerCards=useMemo(()=>{",
"    const pool = teamApi===HOF_KEY",
"      ? applyFilters(cards.filter(c=>hof.includes(c.slug)))",
"      : applyFilters(cards.filter(c=>isNBA(c.slug)&&c.anyTeam?.name===teamApi));",
"    const byL10=(a:any,b:any)=>(b.averageScore??-1)-(a.averageScore??-1);",
"    // Epingles = cartes exactes (doublons autorises), dans l'ordre d'epinglage",
"    const pins=lineup[teamApi]||[];",
"    const pinned=pins.map(s=>pool.find(c=>c.slug===s)).filter(Boolean) as any[];",
"    const pinnedSlugs=new Set(pinned.map((c:any)=>c.slug));",
"    const remaining=pool.filter(c=>!pinnedSlugs.has(c.slug));",
"    // Alphabetique : epingles d'abord puis tri par nom de joueur",
"    if(lockerSort==='collection'){ const alpha=[...remaining].sort((a,b)=>(a.anyPlayer?.lastName||a.name||'').localeCompare(b.anyPlayer?.lastName||b.name||'')); return [...pinned,...alpha]; }",
"    // Mon 5 : uniquement tes epingles d'abord, puis toutes les autres",
"    if(lockerSort==='manual'){ return [...pinned,...remaining]; }",
"    // 5 Majeur : 5 premieres = epingles + meilleurs L10 (joueurs uniques), puis TOUT le reste trie par L10",
"    const pinnedPlayers=new Set(pinned.map(playerKey));",
"    const fill=[...dedupeByPlayer(remaining)].sort(byL10).filter((c:any)=>!pinnedPlayers.has(playerKey(c)));",
"    const head=[...pinned,...fill].slice(0,5);",
"    const headSlugs=new Set(head.map((c:any)=>c.slug));",
"    const tail=pool.filter(c=>!headSlugs.has(c.slug)).sort(byL10);",
"    return [...head,...tail];",
"  },[cards,teamApi,applyFilters,lockerSort,hof,lineup]);",
"",
"  // Galerie = sport + filtres + tri",
"  const galleryTeamList=useMemo(()=>{const ts=new Set<string>();cards.filter(c=>isNBA(c.slug)).forEach(c=>{if(!c.anyTeam?.name)return;if(gConf==='all'||NBA_CONF[c.anyTeam.name]===gConf)ts.add(c.anyTeam.name);});return['all',...Array.from(ts).sort()] as string[];},[cards,gConf]);",
"  const filteredGallery=useMemo(()=>{if(gSport==='foot')return[];let r=applyFilters(cards.filter(c=>isNBA(c.slug)));if(gConf!=='all')r=r.filter(c=>NBA_CONF[c.anyTeam?.name||'']===gConf);if(gTeamCustom!=='all')r=r.filter(c=>(c.anyTeam?.name||'')===gTeamCustom);if(gSort==='rarity')return[...r].sort((a,b)=>(RARITY_ORDER[a.rarityTyped]??9)-(RARITY_ORDER[b.rarityTyped]??9));if(gSort==='score')return[...r].sort((a,b)=>parseFloat(String(b.averageScore||0))-parseFloat(String(a.averageScore||0)));if(gSort==='name')return[...r].sort((a,b)=>(a.anyPlayer?.lastName||'').localeCompare(b.anyPlayer?.lastName||''));return r;},[cards,applyFilters,gSport,gConf,gTeamCustom,gSort]);",
"",
"  const goldGrad='linear-gradient(160deg,#a86f15 0%,#d9a52e 22%,#f7da80 48%,#e8b84a 68%,#b8801a 100%)';",
"  const fBtn=(a:boolean):React.CSSProperties=>({padding:'0.4rem 0.6rem',borderRadius:'0.15rem',border:'none',borderLeft:a?'2px solid #f5d76e':'2px solid rgba(255,255,255,0.08)',background:a?'rgba(245,215,110,0.12)':'rgba(255,255,255,0.025)',color:a?'#f5d76e':'#cfd8e6',cursor:'pointer',fontSize:'0.76rem',fontWeight:a?700:500,transition:'all 0.12s'});",
"  const gridHof:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(155px,1fr))',gap:'12px',padding:'12px'};",
"  const gridMain:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(155px,1fr))',gap:'12px',padding:'12px'};",
"  const galleryBg:React.CSSProperties={background:'radial-gradient(ellipse 130% 90% at 50% -10%,#0d111a 0%,#080b10 50%,#040507 100%)',minHeight:'100vh'};",


"",
"  // Barre de filtres partagee",
"  const labelStyle:React.CSSProperties={fontSize:'0.64rem',fontWeight:800,letterSpacing:'0.14em',textTransform:'uppercase',color:'#eaf2ff',margin:'0.5rem 0 0.3rem 0.5rem'};",
"  const contentBg='linear-gradient(180deg,#13151a 0%,#0c0e12 45%,#07080a 100%)';",
"  const sideBg='rgba(12,14,19,0.82)';",
"",
"  // Bloc filtres vertical (barre laterale)",
"  const rarityOpts=[{value:'all',label:'Toutes les raret\u00e9s'},{value:'common',label:'Common'},{value:'limited',label:'Limited'},{value:'rare',label:'Rare'},{value:'super_rare',label:'Super Rare'},{value:'unique',label:'Unique'}];",
"  const seasonOpts=[{value:'all',label:'Toutes saisons'},...seasonOptions.map(y=>({value:String(y),label:y+'-'+String((y+1)%100).padStart(2,'0')}))];",
"  const specialOpts=[{value:'all',label:'Toutes cartes'},{value:'standard',label:'Standard uniquement'},{value:'special',label:'Sp\u00e9ciales uniquement'},...specialOptions.map(s=>({value:s,label:specialLabel(s)}))];",
"  const Filters=()=>(",
"    <div>",
"      <FilterMenu title='Raret\u00e9' options={rarityOpts} current={fRarity} onSelect={setFRarity}/>",
"      <FilterMenu title='Saison' options={seasonOpts} current={fSeason} onSelect={setFSeason}/>",
"      <FilterMenu title='Cartes sp\u00e9ciales' options={specialOpts} current={fSpecial} onSelect={setFSpecial}/>",
"      <div style={{padding:'0.35rem 0.5rem'}}>",
"        <p style={{fontSize:'0.64rem',fontWeight:800,letterSpacing:'0.14em',textTransform:'uppercase',color:'#eaf2ff',margin:'0 0 0.3rem'}}>Joueur</p>",
"        <input style={{width:'100%',boxSizing:'border-box',background:'rgba(255,255,255,0.05)',color:'#e8eefc',padding:'0.4rem 0.6rem',borderRadius:'0.15rem',border:'1px solid rgba(255,255,255,0.12)',outline:'none',fontSize:'0.78rem'}} placeholder='Rechercher...' value={fPlayer} onChange={e=>setFPlayer(e.target.value)}/>",
"      </div>",
"    </div>",
"  );",
"",
"  return(",
"    <main style={{minHeight:'100vh',background:contentBg,backgroundAttachment:'fixed',color:'white',fontFamily:'system-ui,sans-serif',display:'flex'}}>",
"      <style>{`aside::-webkit-scrollbar,.noscroll::-webkit-scrollbar{width:0;height:0;display:none} .noscroll{scrollbar-width:none} .thin-sb::-webkit-scrollbar{width:6px} .thin-sb::-webkit-scrollbar-thumb{background:rgba(111,195,232,0.45);border-radius:3px} .thin-sb::-webkit-scrollbar-track{background:transparent} .thin-sb{scrollbar-width:thin;scrollbar-color:rgba(111,195,232,0.45) transparent} @keyframes mnflBuild{0%{opacity:0;transform:translateX(-50%) translateY(12px);filter:blur(3.5px) brightness(1.6) saturate(0.4);box-shadow:0 0 28px 7px rgba(111,195,232,0.5)}50%{opacity:0.65;filter:blur(1.5px) brightness(1.2) saturate(0.75)}100%{opacity:1;transform:translateX(-50%) translateY(0);filter:blur(0) brightness(1) saturate(1);box-shadow:0 0 0 0 rgba(111,195,232,0)}} @keyframes mnflSlideLeft{from{opacity:0;transform:translateX(70px);filter:blur(2px)}to{opacity:1;transform:translateX(0);filter:blur(0)}} @keyframes mnflSlideRight{from{opacity:0;transform:translateX(-70px);filter:blur(2px)}to{opacity:1;transform:translateX(0);filter:blur(0)}} @keyframes mnflLaser{0%{height:0;opacity:0.95}50%{height:29%;opacity:1}75%{height:29%;opacity:0.85}100%{height:29%;opacity:0}} @keyframes mnflDeploy{0%{opacity:0;clip-path:inset(0 100% 0 0);transform:perspective(900px) rotateY(-4deg) translateX(-6px)}35%{opacity:0.6}100%{opacity:1;clip-path:inset(0 0% 0 0);transform:perspective(900px) rotateY(0deg) translateX(0)}} @keyframes mnflClose{0%{opacity:1;transform:scaleY(1);filter:brightness(1)}30%{transform:scaleY(0.84);filter:brightness(1.2)}55%{transform:scaleY(0.42);filter:brightness(1.7)}72%{transform:scaleY(0.12);filter:brightness(2.5)}80%{transform:scaleY(0.025);filter:brightness(4) blur(0.5px)}88%{transform:scaleY(0.008);filter:brightness(6);opacity:1}95%{transform:scaleY(0.003);filter:brightness(9)}100%{transform:scaleY(0);opacity:0;filter:brightness(0)}} @keyframes mnflIcebreaker{0%{opacity:0;transform:translate(-50%,-50%) scaleX(0.05) scaleY(1)}18%{opacity:1;transform:translate(-50%,-50%) scaleX(1) scaleY(1);filter:brightness(2)}52%{opacity:1;transform:translate(-50%,-50%) scaleX(1) scaleY(1)}70%{opacity:1;transform:translate(-50%,-50%) scaleX(0.14) scaleY(2.5);filter:brightness(5)}82%{opacity:1;transform:translate(-50%,-50%) scaleX(0.04) scaleY(7);filter:brightness(10)}90%{opacity:1;transform:translate(-50%,-50%) scaleX(0.01) scaleY(2);filter:brightness(4)}100%{opacity:0;transform:translate(-50%,-50%) scaleX(0) scaleY(0)}} @keyframes mnflFloat{0%{transform:translateY(8px);opacity:0}25%{opacity:0.55}75%{opacity:0.45}100%{transform:translateY(-26px);opacity:0}} @keyframes mnflPulse{0%,100%{box-shadow:0 0 9px 1px var(--rc)}50%{box-shadow:0 0 24px 6px var(--rc)}}@keyframes mnflCyanPulse{0%,100%{box-shadow:0 0 12px 3px rgba(64,232,255,0.45),0 0 22px 5px rgba(64,232,255,0.18)}50%{box-shadow:0 0 22px 6px rgba(64,232,255,0.75),0 0 40px 10px rgba(64,232,255,0.32)}}@keyframes mnflCardTrace{0%{stroke-dashoffset:1000}100%{stroke-dashoffset:0}}`}</style>",
"      {/* ===== BARRE LATERALE (glass sombre) ===== */}",
"      <aside style={{position:'fixed',left:0,top:0,width:'220px',height:'100vh',overflow:'visible',background:sideBg,backdropFilter:'blur(12px)',WebkitBackdropFilter:'blur(12px)',borderRight:'1px solid rgba(111,195,232,0.35)',boxShadow:'1px 0 0 rgba(111,195,232,0.25), 6px 0 24px -6px rgba(111,195,232,0.22)',padding:'0.65rem 0.8rem',zIndex:50,scrollbarWidth:'none',display:'flex',flexDirection:'column',gap:'0',fontFamily:\"'Inter','Segoe UI',system-ui,-apple-system,sans-serif\"}}>",
"",
"        {/* ──── HEADER : centré ──── */}",
"        <div style={{textAlign:'center',marginBottom:'0.55rem'}}>",
"          <img src='/logo-pack.png' alt='myNFTlocker' style={{display:'inline-block',width:'70%',filter:'drop-shadow(0 6px 18px rgba(0,0,0,0.6))'}} onError={(e)=>{(e.target as HTMLImageElement).style.display='none';}}/>",
"        </div>",
"        <div style={{display:'flex',flexDirection:'column',gap:'0.4rem',marginBottom:'0.45rem'}}>",
"          {/* Avatar compte (panneau identifiant au clic) */}",
"          <div onClick={()=>setAcctOpen(o=>!o)} style={{display:'flex',alignItems:'center',gap:'0.5rem',padding:'0.3rem 0.4rem',borderRadius:'0.3rem',cursor:'pointer',background:'rgba(255,255,255,0.03)',border:'1px solid rgba(111,195,232,0.18)',transition:'all 0.15s'}} onMouseEnter={e=>{(e.currentTarget as HTMLElement).style.background='rgba(111,195,232,0.08)';}} onMouseLeave={e=>{(e.currentTarget as HTMLElement).style.background='rgba(255,255,255,0.03)';}}>",
"            <div style={{width:'30px',height:'30px',flexShrink:0,borderRadius:'50%',background:'radial-gradient(circle at 35% 30%,#1a1c24,#0a0b0f)',border:'1.5px solid #6fc3e8',boxShadow:'0 0 10px rgba(111,195,232,0.5)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:'0.8rem',fontWeight:900,color:'#6fc3e8'}}>{(slug||'?').trim().charAt(0).toUpperCase()||'?'}</div>",
"            <div style={{flex:1,minWidth:0,textAlign:'left'}}>",
"              <p style={{margin:0,fontSize:'0.72rem',fontWeight:700,color:'#eaf2ff',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{cards.length>0?'Ma collection':'Mon compte'}</p>",
"              <p style={{margin:0,fontSize:'0.56rem',color:'#7a8898'}}>{cards.length>0?(cards.length+' cartes'):'Identifiant Sorare'}</p>",
"            </div>",
"            <span style={{fontSize:'0.6rem',color:'#6fc3e8',opacity:0.8}}>{(acctOpen||cards.length===0)?'\u25B2':'\u25BC'}</span>",
"          </div>",
"          {(acctOpen||cards.length===0)&&(",
"            <input style={{background:'rgba(255,255,255,0.05)',color:'#cfe4fb',padding:'0.4rem 0.65rem',borderRadius:'0.15rem',border:'1px solid rgba(255,255,255,0.1)',outline:'none',fontSize:'0.76rem',boxSizing:'border-box'}} placeholder='ton-slug-sorare' value={slug} onChange={e=>setSlug(e.target.value)} onKeyDown={e=>e.key==='Enter'&&fetchCards()}/>",
"          )}",
"          <button style={{background:goldGrad,color:'#1a0d00',padding:'0.42rem',borderRadius:'0.15rem',border:'none',cursor:'pointer',fontWeight:800,fontSize:'0.8rem',letterSpacing:'0.04em',boxShadow:'0 2px 10px rgba(200,151,30,0.3)'}} onClick={fetchCards}>{loading?'Chargement...':'Voir ma collection'}</button>",
"        </div>",
"",
"        {/* ──── SEGMENTED Vestiaire / Galerie (toujours visible) ──── */}",
"        <div style={{display:'flex',overflow:'hidden',border:'1px solid rgba(255,255,255,0.12)',marginBottom:'0.5rem',clipPath:'polygon(6px 0,100% 0,100% calc(100% - 6px),calc(100% - 6px) 100%,0 100%,0 6px)'}}>",
"          <button style={{flex:1,padding:'0.4rem 0',border:'none',cursor:'pointer',fontSize:'0.76rem',fontWeight:700,background:mode==='locker'?'linear-gradient(160deg,#a86f15 0%,#d9a52e 22%,#f7da80 48%,#e8b84a 68%,#b8801a 100%)':'rgba(255,255,255,0.04)',color:mode==='locker'?'#1a0d00':'#7a8898',transition:'all 0.15s',display:'flex',alignItems:'center',justifyContent:'center',gap:'0.3rem'}} onClick={()=>setMode('locker')}>Vestiaire</button>",
"          <div style={{width:'1px',background:'rgba(255,255,255,0.1)',flexShrink:0}}/>",
"          <button style={{flex:1,padding:'0.4rem 0',border:'none',cursor:'pointer',fontSize:'0.76rem',fontWeight:700,background:mode==='gallery'?'linear-gradient(160deg,#a86f15 0%,#d9a52e 22%,#f7da80 48%,#e8b84a 68%,#b8801a 100%)':'rgba(255,255,255,0.04)',color:mode==='gallery'?'#1a0d00':'#7a8898',transition:'all 0.15s',display:'flex',alignItems:'center',justifyContent:'center',gap:'0.3rem'}} onClick={()=>setMode('gallery')}>Galerie</button>",
"        </div>",
"",
"        {error&&<p style={{color:'#fca5a5',fontSize:'0.7rem',marginBottom:'0.4rem'}}>{error}</p>}",
"",
"        {/* ──── FILTRES : alignés à gauche ──── */}",
"        {cards.length>0&&(",
"          <div style={{textAlign:'left',flex:1}}>",
"            <div style={{borderTop:'1px solid rgba(255,255,255,0.06)',paddingTop:'0.45rem'}}><Filters/></div>",
"            {mode==='locker'&&(",
"              <div style={{marginTop:'0.5rem',padding:'0 0.5rem'}}>",
"                <p style={{fontSize:'0.64rem',fontWeight:800,letterSpacing:'0.14em',textTransform:'uppercase',color:'#eaf2ff',margin:'0 0 0.4rem'}}>Affichage du 5</p>",
"                {/* Segmented control vertical : plat, actif = or */}",
"                <div style={{display:'flex',flexDirection:'column',overflow:'hidden',border:'1px solid rgba(255,255,255,0.12)',clipPath:'polygon(7px 0,100% 0,100% calc(100% - 7px),calc(100% - 7px) 100%,0 100%,0 7px)'}}>",
"                  <button onClick={()=>setLockerSort('majeur')} onMouseEnter={e=>{if(lockerSort!=='majeur'){const t=e.currentTarget as HTMLElement;t.style.color='#6fc3e8';t.style.borderLeftColor='#6fc3e8';}}} onMouseLeave={e=>{if(lockerSort!=='majeur'){const t=e.currentTarget as HTMLElement;t.style.color='rgba(207,216,230,0.62)';t.style.borderLeftColor='transparent';}}} style={{padding:'0.55rem 0.7rem',border:'none',borderLeft:'2px solid '+(lockerSort==='majeur'?'#f5d76e':'transparent'),cursor:'pointer',fontSize:'0.78rem',fontWeight:lockerSort==='majeur'?700:500,textAlign:'left',background:lockerSort==='majeur'?goldGrad:'transparent',color:lockerSort==='majeur'?'#1a0d00':'rgba(207,216,230,0.62)',transition:'all 0.12s'}}>5 Majeur (L10)</button>",
"                  <button onClick={()=>setLockerSort('collection')} onMouseEnter={e=>{if(lockerSort!=='collection'){const t=e.currentTarget as HTMLElement;t.style.color='#6fc3e8';t.style.borderLeftColor='#6fc3e8';}}} onMouseLeave={e=>{if(lockerSort!=='collection'){const t=e.currentTarget as HTMLElement;t.style.color='rgba(207,216,230,0.62)';t.style.borderLeftColor='transparent';}}} style={{padding:'0.55rem 0.7rem',border:'none',borderTop:'1px solid rgba(255,255,255,0.07)',borderLeft:'2px solid '+(lockerSort==='collection'?'#f5d76e':'transparent'),cursor:'pointer',fontSize:'0.78rem',fontWeight:lockerSort==='collection'?700:500,textAlign:'left',background:lockerSort==='collection'?goldGrad:'transparent',color:lockerSort==='collection'?'#1a0d00':'rgba(207,216,230,0.62)',transition:'all 0.12s'}}>Alphab\u00e9tique</button>",
"                  <button onClick={()=>setLockerSort('manual')} onMouseEnter={e=>{if(lockerSort!=='manual'){const t=e.currentTarget as HTMLElement;t.style.color='#6fc3e8';t.style.borderLeftColor='#6fc3e8';}}} onMouseLeave={e=>{if(lockerSort!=='manual'){const t=e.currentTarget as HTMLElement;t.style.color='rgba(207,216,230,0.62)';t.style.borderLeftColor='transparent';}}} style={{padding:'0.55rem 0.7rem',border:'none',borderTop:'1px solid rgba(255,255,255,0.07)',borderLeft:'2px solid '+(lockerSort==='manual'?'#f5d76e':'transparent'),cursor:'pointer',fontSize:'0.78rem',fontWeight:lockerSort==='manual'?700:500,textAlign:'left',background:lockerSort==='manual'?goldGrad:'transparent',color:lockerSort==='manual'?'#1a0d00':'rgba(207,216,230,0.62)',transition:'all 0.12s'}}>Mon 5 majeur</button>",
"                </div>",
"                <button onClick={()=>handleSetDefault(teamApi)} style={{marginTop:'0.4rem',width:'100%',boxSizing:'border-box',padding:'0.45rem 0.7rem',borderRadius:'0.25rem',border:'1px solid',borderColor:defaultTeam===teamApi?'rgba(245,215,110,0.5)':'rgba(255,255,255,0.1)',background:defaultTeam===teamApi?'rgba(245,215,110,0.1)':'transparent',color:defaultTeam===teamApi?'#f5d76e':'#cfd8e6',cursor:'pointer',fontSize:'0.76rem',fontWeight:600,textAlign:'left',transition:'all 0.12s'}}>{defaultTeam===teamApi?'\u2713 Affich\u00e9 en premier':'Afficher en premier'}</button>",
"              </div>",
"            )}",
"            {mode==='gallery'&&(",
"              <div style={{padding:'0 0.5rem',marginTop:'0.5rem'}}>",
"                <p style={{fontSize:'0.64rem',fontWeight:800,letterSpacing:'0.14em',textTransform:'uppercase',color:'#eaf2ff',margin:'0 0 0.35rem'}}>SPORT</p>",
"                <div style={{display:'flex',gap:'0.3rem',marginBottom:'0.55rem'}}>",
"                  {(['nba','foot'] as const).map(s=>(<button key={s} onClick={()=>{setGSport(s);setGConf('all');setGTeamCustom('all');}} style={{flex:1,padding:'0.35rem 0',border:'none',borderLeft:gSport===s?'2px solid #f5d76e':'2px solid rgba(255,255,255,0.1)',background:gSport===s?'rgba(245,215,110,0.12)':'rgba(255,255,255,0.025)',color:gSport===s?'#f5d76e':'#8a9bb0',cursor:'pointer',fontSize:'0.72rem',fontWeight:gSport===s?700:500,borderRadius:'0.2rem',transition:'all 0.12s'}}>{s==='nba'?'NBA':'FOOT'}</button>))}",
"                </div>",
"                {gSport==='nba'&&(",
"                  <>",
"                    <p style={{fontSize:'0.64rem',fontWeight:800,letterSpacing:'0.14em',textTransform:'uppercase',color:'#eaf2ff',margin:'0 0 0.35rem'}}>CONFÉRENCE</p>",
"                    <div style={{display:'flex',gap:'0.3rem',marginBottom:'0.55rem'}}>",
"                      {(['all','Est','Ouest'] as const).map(v=>(<button key={v} onClick={()=>{setGConf(v);setGTeamCustom('all');}} style={{flex:1,padding:'0.32rem 0',border:'none',borderLeft:gConf===v?'2px solid #40e8ff':'2px solid rgba(255,255,255,0.08)',background:gConf===v?'rgba(64,232,255,0.1)':'rgba(255,255,255,0.025)',color:gConf===v?'#40e8ff':'#8a9bb0',cursor:'pointer',fontSize:'0.68rem',fontWeight:gConf===v?700:500,borderRadius:'0.2rem',transition:'all 0.12s'}}>{v==='all'?'Tout':v}</button>))}",
"                    </div>",
"                  </>",
"                )}",
"                <p style={{fontSize:'0.64rem',fontWeight:800,letterSpacing:'0.14em',textTransform:'uppercase',color:'#eaf2ff',margin:'0 0 0.35rem'}}>ÉQUIPE ▾</p>",
"                <div style={{position:'relative',marginBottom:'0.55rem'}}>",
"                  <div onClick={()=>setGDropOpen(o=>!o)} style={{background:'rgba(10,10,12,0.98)',border:gDropOpen?'1px solid rgba(64,232,255,0.5)':'1px solid rgba(64,232,255,0.22)',borderRadius:'0.25rem',padding:'0.38rem 0.6rem',cursor:'pointer',display:'flex',justifyContent:'space-between',alignItems:'center',fontSize:'0.7rem',color:'#cfe4fb',transition:'border-color 0.15s'}}>",
"                    <span style={{overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap',flex:1,paddingRight:'0.4rem'}}>{gTeamCustom==='all'?'Toutes équipes':gTeamCustom}</span>",
"                    <span style={{transform:gDropOpen?'rotate(180deg)':'rotate(0)',transition:'transform 0.2s',flexShrink:0,fontSize:'0.8rem',color:'#40e8ff'}}>\u25be</span>",
"                  </div>",
"                  {gDropOpen&&(",
"                    <div className='gal-scroll' style={{position:'absolute',top:'calc(100% + 3px)',left:0,right:0,maxHeight:'180px',overflowY:'auto',background:'rgba(10,10,12,0.98)',border:'1px solid rgba(64,232,255,0.25)',borderRadius:'0.25rem',zIndex:200,boxShadow:'0 8px 24px rgba(0,0,0,0.7)'}}>",
"                      {galleryTeamList.map((t:string)=>(<div key={t} onClick={()=>{setGTeamCustom(t);setGDropOpen(false);}} style={{padding:'0.35rem 0.65rem',fontSize:'0.7rem',color:t===gTeamCustom?'#40e8ff':'#8a9bb0',cursor:'pointer',borderLeft:t===gTeamCustom?'2px solid #40e8ff':'2px solid transparent',transition:'all 0.1s',background:t===gTeamCustom?'rgba(64,232,255,0.06)':'transparent'}} onMouseEnter={e=>{if(t!==gTeamCustom)(e.currentTarget as HTMLElement).style.background='rgba(64,232,255,0.04)';}} onMouseLeave={e=>{if(t!==gTeamCustom)(e.currentTarget as HTMLElement).style.background='transparent';}}>{t==='all'?'Toutes équipes':t}</div>))}",
"                    </div>",
"                  )}",
"                </div>",
"                <p style={{fontSize:'0.64rem',fontWeight:800,letterSpacing:'0.14em',textTransform:'uppercase',color:'#eaf2ff',margin:'0 0 0.35rem'}}>TRI</p>",
"                <div style={{display:'flex',flexDirection:'column',overflow:'hidden',border:'1px solid rgba(255,255,255,0.1)',borderRadius:'0.2rem',marginBottom:'0.6rem'}}>",
"                  {([['default','Défaut'],['rarity','Rareté'],['score','Score L10'],['name','Nom']] as [string,string][]).map(([v,l],i)=>(<button key={v} onClick={()=>setGSort(v)} style={{padding:'0.4rem 0.6rem',border:'none',borderTop:i>0?'1px solid rgba(255,255,255,0.07)':'none',borderLeft:gSort===v?'2px solid #40e8ff':'2px solid transparent',background:gSort===v?'rgba(64,232,255,0.08)':'transparent',color:gSort===v?'#40e8ff':'rgba(207,216,230,0.6)',cursor:'pointer',fontSize:'0.72rem',fontWeight:gSort===v?700:500,textAlign:'left',transition:'all 0.12s'}}>{l}</button>))}",
"                </div>",
"                <p style={{fontSize:'0.62rem',color:'rgba(255,255,255,0.3)',letterSpacing:'0.1em',marginTop:'0.2rem',fontFamily:'Courier New,monospace'}}>{filteredGallery.length} CARTES</p>",
"              </div>",
"            )}",
"          </div>",
"        )}",
"      </aside>",
"",
"      {/* ===== CONTENU ===== */}",
"      <div style={{flex:1,marginLeft:'220px',minHeight:'100vh'}}>",
"        {cards.length===0&&(",
"          <div style={{display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',minHeight:'100vh',padding:'2rem',textAlign:'center'}}>",
"            <img src='/logo-pack.png' alt='myNFTlocker' style={{width:'260px',maxWidth:'70%',filter:'drop-shadow(0 12px 32px rgba(0,0,0,0.6))'}} onError={(e)=>{(e.target as HTMLImageElement).style.display='none';}}/>",
"            <p style={{color:'#7fb0e0',letterSpacing:'0.25em',textTransform:'uppercase',fontSize:'0.8rem',marginTop:'1.5rem'}}>Entre ton slug Sorare pour commencer</p>",
"          </div>",
"        )}",
"        {cards.length>0&&(",
"          <div style={{padding:'1.5rem 0 2rem'}}>",
"          {/* MODE VESTIAIRE */}",
"          {mode==='locker'&&(",
"            <div style={{maxWidth:'1320px',margin:'0 auto',padding:'0 1rem'}}>",
"              <LockerRoomScene cards={lockerCards} startIndex={lockerStart} hof={hof} flippedSlug={flippedSlug} onFlip={handleFlip} onStar={handleStar} onPin={(s:string)=>handlePin(teamApi,s)} pinnedSlugs={lineup[teamApi]||[]} onPrev={handlePrev} onNext={()=>handleNext(lockerCards.length)} total={lockerCards.length} teamApi={teamApi} teamList={teamList} onTeamChange={handleTeamChange}/>",
"            </div>",
"          )}",
"",
"          {/* MODE GALERIE */}",
"          {mode==='gallery'&&(",
"            <div style={{...galleryBg,minHeight:'100vh'}}>",
"              <GalleryView cards={filteredGallery}/>",
"            </div>",
"          )}",
"          </div>",
"        )}",
"      </div>",
"    </main>",
"  );",
"}",
].join('\n');

fs.writeFileSync('app/page.tsx', page);
console.log('OK - page.tsx: filtres cumulables (rarete, saison, speciales, joueur) vestiaire + galerie');
