const fs=require('fs');
fs.mkdirSync('app/components',{recursive:true});

const lines=[
"'use client';",
"import{useEffect,useRef}from 'react';",
"interface StarCanvasProps{phase?:number;burst?:boolean;}",
"export default function StarCanvas({phase=0,burst=false}:StarCanvasProps){",
"  const canvasRef=useRef<HTMLCanvasElement>(null);",
"  const phaseRef=useRef(phase);",
"  const burstRef=useRef(burst);",
"  useEffect(()=>{phaseRef.current=phase;},[phase]);",
"  useEffect(()=>{burstRef.current=burst;},[burst]);",
"  useEffect(()=>{",
"    const canvas=canvasRef.current!;",
"    const ctx=canvas.getContext('2d')!;",
"    const mouse={x:0,y:0,tx:0,ty:0};",
"    let W=0,H=0;",
"    const resize=()=>{W=canvas.width=window.innerWidth;H=canvas.height=window.innerHeight;};",
"    resize();",
"    window.addEventListener('resize',resize);",
"    const onMouse=(e:MouseEvent)=>{mouse.tx=e.clientX/window.innerWidth-0.5;mouse.ty=e.clientY/window.innerHeight-0.5;};",
"    window.addEventListener('mousemove',onMouse);",
"    // ── Stars : 3 depth layers, CYAN ICEBREAKER dominant ───────────────────",
"    const stars=Array.from({length:320},(_, i)=>{",
"      const depth=i<160?0:i<250?1:2;",
"      // Palette cyan dominante : far=cyan sombre, mid=cyan vif, near=cyan->blanc",
"      const roll=Math.random();",
"      let color;",
"      if(depth===0){color='rgba(0,150,170,';}",
"      else if(depth===1){color=roll>0.2?'rgba(0,225,255,':'rgba(80,210,235,';}",
"      else{color=roll>0.35?'rgba(120,250,255,':'rgba(220,255,255,';}",
"      return{",
"        x:Math.random(),y:Math.random(),",
"        size:depth===0?0.4+Math.random()*0.7:depth===1?0.8+Math.random()*1.2:1.3+Math.random()*2.0,",
"        baseAlpha:depth===0?0.3+Math.random()*0.35:depth===1?0.5+Math.random()*0.4:0.7+Math.random()*0.3,",
"        color,depth,twinkle:Math.random()*Math.PI*2,twSpeed:0.6+Math.random()*1.2,",
"      };",
"    });",
"    // ── Shooting stars (traîne cyan) ───────────────────────────────────────",
"    const shooters:any[]=[];",
"    const spawnShooter=()=>shooters.push({",
"      x:Math.random()*0.75*W,y:Math.random()*0.4*H,",
"      vx:14+Math.random()*11,vy:4+Math.random()*5,",
"      life:1,maxLen:120+Math.random()*130,",
"    });",
"    // ── Asteroids (sombres, lents) ─────────────────────────────────────────",
"    const asteroids=Array.from({length:7},()=>({",
"      x:Math.random()*1600,y:Math.random()*900,",
"      vx:(Math.random()-0.5)*0.32,vy:0.1+Math.random()*0.2,",
"      w:7+Math.random()*9,h:3+Math.random()*5,",
"      rot:Math.random()*Math.PI,vr:(Math.random()-0.5)*0.004,alpha:0.1+Math.random()*0.16,",
"    }));",
"    // ── Energy burst particles (or + cyan, l'impulsion de dispersion) ──────",
"    let particles:any[]=[];",
"    let lastBurst=burstRef.current;",
"    let frame=0;",
"    let raf:number;",
"    const loop=()=>{",
"      raf=requestAnimationFrame(loop);",
"      frame++;",
"      const t=frame*0.016;",
"      // Lissage parallaxe souris",
"      mouse.x+=(mouse.tx-mouse.x)*0.05;mouse.y+=(mouse.ty-mouse.y)*0.05;",
"      // Déclenche l'impulsion d'énergie au front montant de burst",
"      if(burstRef.current&&!lastBurst){",
"        const cx=W/2,cy=H/2;",
"        for(let i=0;i<220;i++){",
"          const angle=(i/220)*Math.PI*2+(Math.random()-0.5)*0.4;",
"          const spd=2.2+Math.random()*10;",
"          const gold=Math.random()>0.4;",
"          particles.push({",
"            x:cx,y:cy,vx:Math.cos(angle)*spd,vy:Math.sin(angle)*spd,",
"            size:1+Math.random()*3.2,alpha:1,decay:0.012+Math.random()*0.008,",
"            r:gold?255:0,g:gold?170+Math.floor(Math.random()*85):225+Math.floor(Math.random()*30),b:gold?10:255,",
"          });",
"        }",
"      }",
"      lastBurst=burstRef.current;",
"      // Clear (fond opaque deep space)",
"      ctx.fillStyle='rgb(1,3,10)';",
"      ctx.fillRect(0,0,W,H);",
"      // Nébuleuse cyan subtile (gradient radial fixe pour densifier l'univers)",
"      const neb=ctx.createRadialGradient(W*0.5,H*0.45,0,W*0.5,H*0.45,Math.max(W,H)*0.6);",
"      neb.addColorStop(0,'rgba(0,80,110,0.10)');",
"      neb.addColorStop(0.5,'rgba(0,40,70,0.04)');",
"      neb.addColorStop(1,'rgba(0,0,0,0)');",
"      ctx.fillStyle=neb;ctx.fillRect(0,0,W,H);",
"      // Stars",
"      for(const s of stars){",
"        const par=[5,14,30][s.depth];",
"        const px=((s.x*W+mouse.x*par)%W+W)%W;",
"        const py=((s.y*H+mouse.y*par)%H+H)%H;",
"        const tw=s.depth>=1?Math.sin(t*s.twSpeed+s.twinkle)*0.3:0;",
"        const a=Math.max(0.04,s.baseAlpha+tw);",
"        ctx.fillStyle=s.color+a.toFixed(2)+')';",
"        ctx.beginPath();ctx.arc(px,py,s.size,0,Math.PI*2);ctx.fill();",
"        if(s.depth===2&&s.size>2.1){",
"          ctx.fillStyle=s.color+(a*0.22).toFixed(2)+')';",
"          ctx.beginPath();ctx.arc(px,py,s.size*3,0,Math.PI*2);ctx.fill();",
"        }",
"      }",
"      // Shooting stars",
"      if(frame%270===0)spawnShooter();",
"      for(let i=shooters.length-1;i>=0;i--){",
"        const s=shooters[i];",
"        s.x+=s.vx;s.y+=s.vy;s.life-=0.02;",
"        if(s.life<=0||s.x>W+200){shooters.splice(i,1);continue;}",
"        const tx=s.x-s.vx*(s.maxLen/s.vx),ty=s.y-s.vy*(s.maxLen/s.vx);",
"        const g=ctx.createLinearGradient(tx,ty,s.x,s.y);",
"        g.addColorStop(0,'rgba(0,255,255,0)');",
"        g.addColorStop(0.6,'rgba(120,240,255,'+(s.life*0.35).toFixed(2)+')');",
"        g.addColorStop(1,'rgba(220,255,255,'+s.life.toFixed(2)+')');",
"        ctx.strokeStyle=g;ctx.lineWidth=s.life*2.2;",
"        ctx.shadowColor='rgba(0,230,255,0.8)';ctx.shadowBlur=12;",
"        ctx.beginPath();ctx.moveTo(tx,ty);ctx.lineTo(s.x,s.y);ctx.stroke();",
"        ctx.shadowBlur=0;",
"      }",
"      // Asteroids",
"      for(const a of asteroids){",
"        a.x+=a.vx;a.y+=a.vy;a.rot+=a.vr;",
"        if(a.y>H+30){a.y=-30;a.x=Math.random()*W;}",
"        if(a.x>W+30)a.x=-30;if(a.x<-30)a.x=W+30;",
"        ctx.save();ctx.translate(a.x,a.y);ctx.rotate(a.rot);",
"        ctx.globalAlpha=a.alpha;",
"        ctx.fillStyle='#141a26';",
"        ctx.beginPath();ctx.ellipse(0,0,a.w,a.h,0,0,Math.PI*2);ctx.fill();",
"        ctx.globalAlpha=a.alpha*0.5;ctx.fillStyle='#222b40';",
"        ctx.beginPath();ctx.ellipse(-a.w*0.25,-a.h*0.25,a.w*0.5,a.h*0.4,0.4,0,Math.PI*2);ctx.fill();",
"        ctx.restore();ctx.globalAlpha=1;",
"      }",
"      // Energy burst particles",
"      for(let i=particles.length-1;i>=0;i--){",
"        const p=particles[i];",
"        p.x+=p.vx;p.y+=p.vy;p.vx*=0.965;p.vy*=0.965;p.alpha-=p.decay;",
"        if(p.alpha<=0){particles.splice(i,1);continue;}",
"        const col='rgba('+p.r+','+p.g+','+p.b+','+p.alpha.toFixed(2)+')';",
"        ctx.shadowColor=col;ctx.shadowBlur=10;",
"        ctx.fillStyle=col;",
"        ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill();",
"      }",
"      ctx.shadowBlur=0;ctx.globalAlpha=1;",
"    };",
"    loop();",
"    return()=>{cancelAnimationFrame(raf);window.removeEventListener('resize',resize);window.removeEventListener('mousemove',onMouse);};",
"  },[]);",
"  return <canvas ref={canvasRef} style={{position:'fixed',inset:0,zIndex:0,width:'100%',height:'100%',background:'rgb(1,3,10)'}}/>;",
"}",
];

fs.writeFileSync('app/components/StarCanvas.tsx',lines.join('\n'),'utf8');
console.log('OK - StarCanvas.tsx (cyan icebreaker, 320 stars, burst prop, nebula)');
