const fs = require('fs');
if (!fs.existsSync('app/components')) fs.mkdirSync('app/components', { recursive: true });

const lockerRoom = [
"'use client';",
"import { Canvas, useThree } from '@react-three/fiber';",
"import { Html } from '@react-three/drei';",
"import { useRef, useEffect, memo } from 'react';",
"import * as THREE from 'three';",
"",
"const RARITY_GLOW: Record<string,string> = {",
"  common:'0 0 18px 6px rgba(220,220,255,0.5)',",
"  limited:'0 0 24px 8px rgba(234,179,8,0.85)',",
"  rare:'0 0 28px 9px rgba(59,130,246,0.9)',",
"  super_rare:'0 0 32px 11px rgba(239,68,68,0.95)',",
"  unique:'0 0 38px 13px rgba(168,85,247,1)',",
"};",
"const RARITY_COLOR: Record<string,string> = {",
"  common:'#9ca3af', limited:'#eab308', rare:'#3b82f6', super_rare:'#ef4444', unique:'#a855f7',",
"};",
"const RARITY_FILL: Record<string,string> = {",
"  common:'#a8a8b5', limited:'#b48a14', rare:'#1e4ba8', super_rare:'#a82a2a', unique:'#7e3fc4',",
"};",
"const isNBA = (slug: string) => /\\d{8}/.test(slug);",
"const parseCard = (name: string) => {",
"  const parts = name.split('\u2022');",
"  const left = parts[0].trim(); const right=(parts[1]||'').trim();",
"  const sm = left.match(/(\\d{4}-\\d{2})/); const season=sm?sm[1]:'';",
"  const pn = left.replace(/\\d{4}-\\d{2}/,'').trim();",
"  const lastName = pn.split(' ').pop()!.toUpperCase();",
"  const sr = right.match(/(\\d+\\/\\d+)/);",
"  return { lastName, season, serial:sr?sr[1]:null };",
"};",
"const nfs=(l:number)=>l<=5?'1.7rem':l<=7?'1.45rem':l<=9?'1.2rem':l<=11?'1rem':'0.85rem';",
"",
"// ── BACK DE CARTE ──────────────────────────────────",
"const CBack = memo(({card,rc}:any)=>{",
"  const {season,serial}=parseCard(card.name);",
"  const ln=(card.anyPlayer?.lastName||parseCard(card.name).lastName).toUpperCase();",
"  const sn=card.anyPlayer?.shirtNumber??null;",
"  return(",
"    <div style={{position:'absolute',top:0,left:0,right:0,bottom:0,backfaceVisibility:'hidden',WebkitBackfaceVisibility:'hidden',transform:'rotateY(180deg)',borderRadius:'0.4rem',overflow:'hidden',background:'radial-gradient(ellipse at center,#15151f,#07070d)',display:'flex',flexDirection:'column',borderTop:'3px solid '+rc,borderBottom:'3px solid '+rc}}>",
"      <div style={{padding:'0.4rem',borderBottom:'1px solid rgba(255,255,255,0.06)',textAlign:'center'}}>",
"        <p style={{margin:0,fontSize:'0.65rem',color:rc,fontWeight:800,letterSpacing:'0.06em'}}>myNFTlocker</p>",
"        <p style={{margin:'2px 0 0',fontSize:'0.48rem',color:'#6b7280'}}>{isNBA(card.slug)?'NBA':'FOOT'} \u2022 {season}</p>",
"      </div>",
"      <div style={{flex:1,display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',padding:'0.3rem'}}>",
"        <p style={{margin:0,fontSize:nfs(ln.length),fontWeight:900,color:'#fff',lineHeight:1.1,textAlign:'center',textShadow:'0 0 20px '+rc+'99'}}>{ln}</p>",
"        {sn!==null&&<p style={{margin:'0.2rem 0 0',fontSize:'0.95rem',color:rc,fontWeight:900}}>#{sn}</p>}",
"        {serial&&<p style={{margin:'0.1rem 0 0',fontSize:'0.5rem',color:'#6b7280'}}>{serial}</p>}",
"        <p style={{margin:'0.4rem 0 0',fontSize:'1.2rem',fontWeight:800,color:'#fff'}}>--</p>",
"        <p style={{margin:0,fontSize:'0.45rem',color:'#9ca3af',letterSpacing:'0.2em',textTransform:'uppercase'}}>L10</p>",
"      </div>",
"      <div style={{padding:'0.25rem',borderTop:'1px solid rgba(255,255,255,0.06)'}}>",
"        <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:'0.1rem'}}>",
"          {[['BL10','--'],['GW','--'],['HS','--'],['REW','--']].map(([l,v])=>(",
"            <div key={l} style={{textAlign:'center'}}>",
"              <p style={{margin:0,fontSize:'0.6rem',fontWeight:800,color:'#e5e7eb'}}>{v}</p>",
"              <p style={{margin:0,fontSize:'0.32rem',color:'#6b7280',textTransform:'uppercase'}}>{l}</p>",
"            </div>",
"          ))}",
"        </div>",
"      </div>",
"      <div style={{padding:'0.2rem 0.35rem 0.35rem',display:'flex',justifyContent:'center',gap:'0.25rem'}}>",
"        <span style={{padding:'0.1rem 0.35rem',borderRadius:'999px',border:'1px solid '+rc+'55',background:'#000a',fontSize:'0.42rem',fontWeight:800,color:rc}}>BONUS --</span>",
"        <span style={{padding:'0.1rem 0.35rem',borderRadius:'999px',border:'1px solid '+rc+'55',background:rc+'12',fontSize:'0.42rem',fontWeight:700,color:rc,textTransform:'uppercase'}}>{card.rarityTyped.replace('_',' ')}</span>",
"      </div>",
"    </div>",
"  );",
"});",
"CBack.displayName='CBack';",
"",
"// ── CARTE RECTO ───────────────────────────────────",
"const CItem = memo(({card,isFlipped,isStarred,onFlip,onStar}:any)=>{",
"  const glow=RARITY_GLOW[card.rarityTyped]||RARITY_GLOW.common;",
"  const fill=RARITY_FILL[card.rarityTyped]||RARITY_FILL.common;",
"  const rc=RARITY_COLOR[card.rarityTyped]||'#9ca3af';",
"  return(",
"    <div style={{perspective:'900px',cursor:'pointer',width:'150px'}} onClick={()=>onFlip(card.slug)}>",
"      <div style={{position:'relative',transformStyle:'preserve-3d',transition:'transform 0.45s ease',transform:isFlipped?'rotateY(180deg)':'rotateY(0deg)',boxShadow:glow,borderRadius:'0.4rem',background:fill}}>",
"        <div style={{backfaceVisibility:'hidden',WebkitBackfaceVisibility:'hidden',borderRadius:'0.4rem',overflow:'hidden'}}>",
"          <button style={{position:'absolute',top:'5px',right:'5px',background:isStarred?'#7c3aedcc':'#00000099',border:'none',borderRadius:'50%',width:'22px',height:'22px',cursor:'pointer',fontSize:'11px',display:'flex',alignItems:'center',justifyContent:'center',zIndex:10}}",
"            onClick={e=>{e.stopPropagation();onStar(card.slug);}}>",
"            {isStarred?'\u2B50':'\u2606'}",
"          </button>",
"          <img src={card.pictureUrl} alt={card.name} style={{width:'150px',height:'auto',display:'block'}}/>",
"        </div>",
"        <CBack card={card} rc={rc}/>",
"      </div>",
"    </div>",
"  );",
"});",
"CItem.displayName='CItem';",
"",
"// ── CASIER CSS (frame autour de la carte) ──────────",
"const LockerFrame = memo(({card,isFlipped,isStarred,onFlip,onStar}:any)=>{",
"  const {lastName}=parseCard(card.name);",
"  const dn=(card.anyPlayer?.lastName||lastName).toUpperCase();",
"  const wallDark='#0e0804';",
"  const wallMid='#1a0e06';",
"  const sideW=18;",
"  return(",
"    <div style={{display:'flex',flexDirection:'column',width:String(150+sideW*2)+'px'}}>",
"",
"      {/* Plafond du casier avec spot */}",
"      <div style={{height:'44px',background:'linear-gradient(180deg,#160c04 0%,#0c0703 100%)',borderLeft:sideW+'px solid '+wallDark,borderRight:sideW+'px solid '+wallDark,position:'relative',overflow:'visible'}}>",
"        {/* Rail plafond */}",
"        <div style={{position:'absolute',bottom:0,left:-sideW,right:-sideW,height:'5px',background:'linear-gradient(90deg,#2a1a0a,#5a3815,#2a1a0a)'}}/>",
"        {/* Boitier spot */}",
"        <div style={{position:'absolute',bottom:'5px',left:'50%',transform:'translateX(-50%)',width:'16px',height:'10px',background:'#1e1208',borderRadius:'3px 3px 0 0',border:'1px solid rgba(255,255,255,0.08)'}}/>",
"        {/* Ampoule + halo */}",
"        <div style={{position:'absolute',bottom:'2px',left:'50%',transform:'translateX(-50%)',width:'9px',height:'9px',background:'radial-gradient(circle,#fff8e0 0%,#ffd060 60%,transparent 100%)',borderRadius:'50%',boxShadow:'0 0 14px 8px rgba(255,200,70,0.65)',zIndex:3}}/>",
"        {/* Cone de lumiere */}",
"        <div style={{position:'absolute',top:'14px',left:'50%',transform:'translateX(-50%)',width:'120px',height:'80px',background:'radial-gradient(ellipse 60% 100% at 50% 0%,rgba(255,195,70,0.18) 0%,transparent 70%)',pointerEvents:'none'}}/>",
"      </div>",
"",
"      {/* Corps du casier avec la carte */}",
"      <div style={{",
"        background:wallDark,",
"        borderLeft:sideW+'px solid '+wallDark,",
"        borderRight:sideW+'px solid '+wallDark,",
"        position:'relative',",
"        boxShadow:'inset '+sideW+'px 0 '+sideW+'px rgba(0,0,0,0.75), inset -'+sideW+'px 0 '+sideW+'px rgba(0,0,0,0.75)',",
"      }}>",
"        {/* Ombre zénithale sur la carte */}",
"        <div style={{position:'absolute',top:0,left:0,right:0,height:'40px',background:'linear-gradient(180deg,rgba(255,195,70,0.09) 0%,transparent 100%)',pointerEvents:'none',zIndex:1}}/>",
"        <div style={{position:'relative',zIndex:2}}>",
"          <CItem card={card} isFlipped={isFlipped} isStarred={isStarred} onFlip={onFlip} onStar={onStar}/>",
"        </div>",
"      </div>",
"",
"      {/* Tablette */}",
"      <div style={{height:'20px',background:'linear-gradient(180deg,#9a6535 0%,#6a3e18 50%,#3a1e08 100%)',borderLeft:sideW+'px solid '+wallDark,borderRight:sideW+'px solid '+wallDark,boxShadow:'0 8px 20px rgba(0,0,0,0.9)',position:'relative'}}>",
"        <div style={{position:'absolute',top:0,left:0,right:0,height:'2px',background:'rgba(255,255,255,0.18)'}}/>",
"      </div>",
"",
"      {/* Plaque gravee */}",
"      <div style={{background:'#080502',borderLeft:sideW+'px solid '+wallMid,borderRight:sideW+'px solid '+wallMid,padding:'5px 0 7px',display:'flex',justifyContent:'center'}}>",
"        <div style={{background:'linear-gradient(135deg,#f5d76e 0%,#c9a227 45%,#f0cc50 55%,#9a7010 100%)',padding:'4px 14px',borderRadius:'2px',boxShadow:'inset 0 1px 3px rgba(0,0,0,0.55),0 2px 6px rgba(0,0,0,0.7)',border:'1px solid rgba(0,0,0,0.4)',maxWidth:'140px'}}>",
"          <span style={{fontSize:'0.6rem',fontWeight:900,color:'#2a1800',letterSpacing:'0.13em',textTransform:'uppercase',fontFamily:'Georgia,serif',textShadow:'0 1px 0 rgba(255,255,255,0.25)',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis',display:'block',maxWidth:'130px'}}>{dn}</span>",
"        </div>",
"      </div>",
"    </div>",
"  );",
"});",
"LockerFrame.displayName='LockerFrame';",
"",
"// ── GEOMETRIE 3D DE LA SALLE ──────────────────────",
"function Room(){",
"  return(",
"    <group>",
"      {/* Mur arriere */}",
"      <mesh position={[0,1,-3.2]}><boxGeometry args={[20,9,0.2]}/><meshStandardMaterial color='#120805' roughness={0.93}/></mesh>",
"      {/* Boiseries horizontales mur arriere */}",
"      {[2.5,0,-2].map((y,i)=>(",
"        <mesh key={i} position={[0,y,-3.15]}><boxGeometry args={[20,0.18,0.12]}/><meshStandardMaterial color='#2a1406' roughness={0.85}/></mesh>",
"      ))}",
"      {/* Separateurs verticaux (entre casiers) */}",
"      {[-8,-4.8,-1.6,1.6,4.8,8].map((x,i)=>(",
"        <mesh key={i} position={[x,0.5,-3.1]}><boxGeometry args={[0.25,8,0.5]}/><meshStandardMaterial color='#1e0e05' roughness={0.9}/></mesh>",
"      ))}",
"      {/* Plafond */}",
"      <mesh position={[0,3.8,0]}><boxGeometry args={[20,0.3,8]}/><meshStandardMaterial color='#0a0500' roughness={1}/></mesh>",
"      {/* Rail plafond avant */}",
"      <mesh position={[0,3.5,-3]}><boxGeometry args={[20,0.2,0.4]}/><meshStandardMaterial color='#1e0e05' roughness={0.88}/></mesh>",
"      {/* PARQUET - planches alternees */}",
"      {Array.from({length:14},(_,i)=>(",
"        <mesh key={i} rotation={[-Math.PI/2,0,0]} position={[0,-2.6,i*0.6-3.5]}>",
"          <planeGeometry args={[20,0.58]}/>",
"          <meshStandardMaterial color={i%2===0?'#5a2e10':'#4a2408'} roughness={0.62} metalness={0.04}/>",
"        </mesh>",
"      ))}",
"      {/* Lignes entre planches */}",
"      {Array.from({length:15},(_,i)=>(",
"        <mesh key={i} rotation={[-Math.PI/2,0,0]} position={[0,-2.59,i*0.6-3.8]}>",
"          <planeGeometry args={[20,0.04]}/>",
"          <meshStandardMaterial color='#1a0a04' roughness={0.9}/>",
"        </mesh>",
"      ))}",
"      {/* Murs lateraux (suggestion de profondeur) */}",
"      <mesh position={[-9,1,0]} rotation={[0,Math.PI/5,0]}><boxGeometry args={[0.2,9,8]}/><meshStandardMaterial color='#0e0603' roughness={0.96}/></mesh>",
"      <mesh position={[9,1,0]} rotation={[0,-Math.PI/5,0]}><boxGeometry args={[0.2,9,8]}/><meshStandardMaterial color='#0e0603' roughness={0.96}/></mesh>",
"      {/* Banc devant */}",
"      <mesh position={[0,-1.8,1.5]}><boxGeometry args={[18,0.2,1]}/><meshStandardMaterial color='#6a3e18' roughness={0.7}/></mesh>",
"      <mesh position={[-8,-2.2,1.5]}><boxGeometry args={[0.15,0.8,1]}/><meshStandardMaterial color='#3a1e08' roughness={0.85}/></mesh>",
"      <mesh position={[8,-2.2,1.5]}><boxGeometry args={[0.15,0.8,1]}/><meshStandardMaterial color='#3a1e08' roughness={0.85}/></mesh>",
"    </group>",
"  );",
"}",
"",
"// ── SPOT PAR CASIER ──────────────────────────────",
"function Spot({x}:{x:number}){",
"  const {scene}=useThree();",
"  const ref=useRef<THREE.SpotLight>(null!);",
"  useEffect(()=>{",
"    const t=new THREE.Object3D();",
"    t.position.set(x,-1,-2.8);",
"    scene.add(t);",
"    if(ref.current) ref.current.target=t;",
"    return ()=>{scene.remove(t);};",
"  },[x,scene]);",
"  return <spotLight ref={ref} position={[x,4.5,0.5]} angle={0.3} penumbra={0.6} intensity={160} color='#ffc870' distance={12}/>;",
"}",
"",
"const CARD_X=[-6.4,-3.2,0,3.2,6.4];",
"",
"interface Props{",
"  cards:any[]; startIndex:number; hof:string[]; flippedSlug:string|null;",
"  onFlip:(s:string)=>void; onStar:(s:string)=>void;",
"  onPrev:()=>void; onNext:()=>void; total:number;",
"}",
"",
"export default function LockerRoomScene({cards,startIndex,hof,flippedSlug,onFlip,onStar,onPrev,onNext,total}:Props){",
"  const visible=cards.slice(startIndex,startIndex+5);",
"  const hasPrev=startIndex>0;",
"  const hasNext=startIndex+5<total;",
"  const from=startIndex+1; const to=Math.min(startIndex+5,total);",
"  return(",
"    <div style={{position:'relative',width:'100%',height:'76vh',background:'#060200'}}>",
"      <Canvas camera={{position:[0,0.2,9],fov:58}} shadows={false}>",
"        <ambientLight intensity={0.03} color='#180800'/>",
"        {CARD_X.map(x=><Spot key={x} x={x}/>)}",
"        <Room/>",
"        {visible.map((card,i)=>(",
"          <Html key={card.slug} position={[CARD_X[i],0.2,-1.4]} center distanceFactor={9} zIndexRange={[100,0]}>",
"            <LockerFrame",
"              card={card}",
"              isFlipped={flippedSlug===card.slug}",
"              isStarred={hof.includes(card.slug)}",
"              onFlip={onFlip}",
"              onStar={onStar}",
"            />",
"          </Html>",
"        ))}",
"      </Canvas>",
"      {hasPrev&&(",
"        <button onClick={onPrev} style={{position:'absolute',left:'1.2rem',top:'50%',transform:'translateY(-50%)',background:'rgba(0,0,0,0.8)',border:'2px solid #c9a227',color:'#c9a227',borderRadius:'50%',width:'52px',height:'52px',fontSize:'1.5rem',cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center',zIndex:20,boxShadow:'0 0 15px rgba(201,162,39,0.35)'}}>",
"          \u25C0",
"        </button>",
"      )}",
"      {hasNext&&(",
"        <button onClick={onNext} style={{position:'absolute',right:'1.2rem',top:'50%',transform:'translateY(-50%)',background:'rgba(0,0,0,0.8)',border:'2px solid #c9a227',color:'#c9a227',borderRadius:'50%',width:'52px',height:'52px',fontSize:'1.5rem',cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center',zIndex:20,boxShadow:'0 0 15px rgba(201,162,39,0.35)'}}>",
"          \u25B6",
"        </button>",
"      )}",
"      <div style={{position:'absolute',bottom:'0.8rem',left:'50%',transform:'translateX(-50%)',color:'#c9a22788',fontSize:'0.72rem',letterSpacing:'0.15em',zIndex:10}}>",
"        {from}-{to} / {total}",
"      </div>",
"    </div>",
"  );",
"}",
].join('\n');

fs.writeFileSync('app/components/LockerRoom.tsx', lockerRoom);
console.log('OK - Casiers CSS complets, parquet, banc, separateurs, spots corriges.');
