const fs = require('fs');

const page = [
"'use client';",
"import { useState, useEffect, memo, useCallback } from 'react';",
"import dynamic from 'next/dynamic';",
"",
"const LockerRoomScene = dynamic(() => import('./components/LockerRoom'), { ssr: false });",
"",
"const RARITY_GLOW: Record<string,string> = {",
"  common:'0 0 16px 5px rgba(220,220,255,0.45)',",
"  limited:'0 0 22px 7px rgba(234,179,8,0.75)',",
"  rare:'0 0 26px 8px rgba(59,130,246,0.85)',",
"  super_rare:'0 0 30px 10px rgba(239,68,68,0.9)',",
"  unique:'0 0 36px 12px rgba(168,85,247,0.95)',",
"};",
"const RARITY_COLOR: Record<string,string> = {",
"  common:'#9ca3af', limited:'#eab308', rare:'#3b82f6', super_rare:'#ef4444', unique:'#a855f7',",
"};",
"const RARITY_FILL: Record<string,string> = {",
"  common:'#a8a8b5', limited:'#b48a14', rare:'#1e4ba8', super_rare:'#a82a2a', unique:'#7e3fc4',",
"};",
"const RARITY_ORDER: Record<string,number> = { unique:0, super_rare:1, rare:2, limited:3, common:4 };",
"const isNBA = (slug: string) => /\\d{8}/.test(slug);",
"const parseCard = (name: string) => {",
"  const parts = name.split('\u2022');",
"  const left = parts[0].trim(); const right = (parts[1]||'').trim();",
"  const sm = left.match(/(\\d{4}-\\d{2})/); const season = sm?sm[1]:'';",
"  const pn = left.replace(/\\d{4}-\\d{2}/,'').trim();",
"  const ln = pn.split(' ').pop()!.toUpperCase();",
"  const sr = right.match(/(\\d+\\/\\d+)/);",
"  return { playerName:pn, lastName:ln, season, serial:sr?sr[1]:null };",
"};",
"const nameFontSize = (l: number) => l<=5?'2rem':l<=7?'1.65rem':l<=9?'1.35rem':l<=11?'1.1rem':'0.9rem';",
"",
"const CardBack = memo(({ card }: { card: any }) => {",
"  const { season, serial } = parseCard(card.name);",
"  const rc = RARITY_COLOR[card.rarityTyped]||'#9ca3af';",
"  const lastName = (card.anyPlayer?.lastName||parseCard(card.name).lastName).toUpperCase();",
"  const shirtNumber = card.anyPlayer?.shirtNumber??null;",
"  return (",
"    <div style={{ position:'absolute',top:0,left:0,right:0,bottom:0,backfaceVisibility:'hidden',transform:'rotateY(180deg)',borderRadius:'0.4rem',overflow:'hidden',background:'radial-gradient(ellipse at center,#15151f 0%,#07070d 100%)',display:'flex',flexDirection:'column',borderTop:'3px solid '+rc,borderBottom:'3px solid '+rc }}>",
"      <div style={{ padding:'0.5rem',borderBottom:'1px solid rgba(255,255,255,0.06)',textAlign:'center' }}>",
"        <p style={{ margin:0,fontSize:'0.75rem',color:rc,fontWeight:800,letterSpacing:'0.06em' }}>myNFTlocker</p>",
"        <p style={{ margin:'2px 0 0',fontSize:'0.55rem',color:'#6b7280' }}>{isNBA(card.slug)?'NBA':'FOOTBALL'} \u2022 {season}</p>",
"      </div>",
"      <div style={{ padding:'0.4rem',textAlign:'center' }}>",
"        <p style={{ margin:0,fontSize:nameFontSize(lastName.length),fontWeight:900,color:'#fff',lineHeight:1.1,textShadow:'0 0 18px '+rc+'99' }}>{lastName}</p>",
"        {shirtNumber!==null&&<p style={{ margin:'0.25rem 0 0',fontSize:'1.1rem',color:rc,fontWeight:900 }}>#{shirtNumber}</p>}",
"        {serial&&<p style={{ margin:'0.1rem 0 0',fontSize:'0.6rem',color:'#6b7280' }}>{serial}</p>}",
"      </div>",
"      <div style={{ flex:1,display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center' }}>",
"        <p style={{ margin:0,fontSize:'1.5rem',fontWeight:800,color:'#fff' }}>--</p>",
"        <p style={{ margin:0,fontSize:'0.55rem',color:'#9ca3af',letterSpacing:'0.2em',textTransform:'uppercase',fontWeight:700 }}>L10</p>",
"      </div>",
"      <div style={{ padding:'0.3rem',borderTop:'1px solid rgba(255,255,255,0.06)' }}>",
"        <div style={{ display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:'0.15rem' }}>",
"          {[['BEAT L10','--'],['GW','--'],['HSCORE','--'],['REWARDS','--']].map(([l,v])=>(",
"            <div key={l} style={{ textAlign:'center' }}>",
"              <p style={{ margin:0,fontSize:'0.7rem',fontWeight:800,color:'#e5e7eb' }}>{v}</p>",
"              <p style={{ margin:'1px 0 0',fontSize:'0.38rem',color:'#6b7280',letterSpacing:'0.08em',textTransform:'uppercase' }}>{l}</p>",
"            </div>",
"          ))}",
"        </div>",
"      </div>",
"      <div style={{ padding:'0.3rem 0.5rem 0.45rem',display:'flex',justifyContent:'center',gap:'0.4rem' }}>",
"        <span style={{ padding:'0.15rem 0.5rem',borderRadius:'999px',border:'1px solid '+rc+'66',background:'#000a',fontSize:'0.55rem',fontWeight:800,color:rc }}>BONUS --</span>",
"        <span style={{ padding:'0.15rem 0.5rem',borderRadius:'999px',border:'1px solid '+rc+'66',background:rc+'15',fontSize:'0.55rem',fontWeight:700,color:rc,textTransform:'uppercase' }}>{card.rarityTyped.replace('_',' ')}</span>",
"      </div>",
"    </div>",
"  );",
"});",
"CardBack.displayName='CardBack';",
"",
"const CardItem = memo(({ card, isFlipped, isStarred, onFlip, onStar }: any) => {",
"  const glow = RARITY_GLOW[card.rarityTyped]||RARITY_GLOW.common;",
"  const fill = RARITY_FILL[card.rarityTyped]||RARITY_FILL.common;",
"  return (",
"    <div style={{ perspective:'1200px',cursor:'pointer' }} onClick={()=>onFlip(card.slug)}>",
"      <div style={{ position:'relative',transformStyle:'preserve-3d',transition:'transform 0.45s ease',transform:isFlipped?'rotateY(180deg)':'rotateY(0deg)',boxShadow:glow,borderRadius:'0.4rem',background:fill }}>",
"        <div style={{ backfaceVisibility:'hidden',borderRadius:'0.4rem',overflow:'hidden' }}>",
"          <button style={{ position:'absolute',top:'6px',right:'6px',background:isStarred?'#7c3aedcc':'#00000099',border:'none',borderRadius:'50%',width:'26px',height:'26px',cursor:'pointer',fontSize:'13px',display:'flex',alignItems:'center',justifyContent:'center',zIndex:10 }}",
"            onClick={e=>{e.stopPropagation();onStar(card.slug);}}>",
"            {isStarred?'\u2B50':'\u2606'}",
"          </button>",
"          <img src={card.pictureUrl} alt={card.name} loading='lazy' style={{ width:'100%',height:'auto',display:'block' }} />",
"        </div>",
"        <CardBack card={card} />",
"      </div>",
"    </div>",
"  );",
"});",
"CardItem.displayName='CardItem';",
"",
"const LockerSlot = memo(({ card, isFlipped, isStarred, isHof, onFlip, onStar }: any) => {",
"  const { lastName } = parseCard(card.name);",
"  const dn = (card.anyPlayer?.lastName||lastName).toUpperCase();",
"  const sp = isHof?'rgba(255,210,80,0.2)':'rgba(255,185,80,0.1)';",
"  const wall = isHof?'#100e00':'#080402';",
"  const pg = isHof?'linear-gradient(135deg,#f5d76e,#c9a227,#f0cc50,#9a7010)':'linear-gradient(135deg,#d4a96a,#8b5e2a,#c8a060,#5a3510)';",
"  const pt = isHof?'#2a1c00':'#1a0c04';",
"  return (",
"    <div style={{ display:'flex',flexDirection:'column' }}>",
"      <div style={{ height:'30px',background:isHof?'linear-gradient(180deg,#1e1800,#0f0c00)':'linear-gradient(180deg,#160c04,#0a0603)',position:'relative' }}>",
"        <div style={{ position:'absolute',bottom:0,left:0,right:0,height:'4px',background:isHof?'linear-gradient(90deg,#3a2e00,#6a5500,#3a2e00)':'linear-gradient(90deg,#2a1a0a,#4a2e10,#2a1a0a)' }}/>",
"        <div style={{ position:'absolute',bottom:'0px',left:'50%',transform:'translateX(-50%)',width:'10px',height:'10px',background:'radial-gradient(circle,#fff8e0,#ffd060 60%,transparent)',borderRadius:'50%',boxShadow:isHof?'0 0 12px 6px rgba(255,210,80,0.7)':'0 0 10px 4px rgba(255,185,80,0.5)',zIndex:3 }}/>",
"      </div>",
"      <div style={{ background:wall,position:'relative',overflow:'hidden',padding:'6px 6px 6px' }}>",
"        <div style={{ position:'absolute',top:0,left:'50%',transform:'translateX(-50%)',width:'100%',height:'100%',background:'radial-gradient(ellipse 80% 55% at 50% 0%,'+sp+',transparent 65%)',pointerEvents:'none',zIndex:1 }}/>",
"        <div style={{ position:'absolute',top:0,left:0,width:'18%',height:'100%',background:'linear-gradient(90deg,rgba(0,0,0,0.65),transparent)',pointerEvents:'none',zIndex:1 }}/>",
"        <div style={{ position:'absolute',top:0,right:0,width:'18%',height:'100%',background:'linear-gradient(270deg,rgba(0,0,0,0.65),transparent)',pointerEvents:'none',zIndex:1 }}/>",
"        <div style={{ position:'relative',zIndex:2 }}>",
"          <CardItem card={card} isFlipped={isFlipped} isStarred={isStarred} onFlip={onFlip} onStar={onStar}/>",
"        </div>",
"      </div>",
"      <div style={{ height:'16px',background:isHof?'linear-gradient(180deg,#e8c456,#b8941e,#6a4e00)':'linear-gradient(180deg,#8a5a2e,#5a3210,#2e1606)',boxShadow:'0 6px 16px rgba(0,0,0,0.9)',position:'relative' }}>",
"        <div style={{ position:'absolute',top:0,left:0,right:0,height:'2px',background:'rgba(255,255,255,0.15)' }}/>",
"      </div>",
"      <div style={{ background:isHof?'#080600':'#050302',padding:'4px 4px 5px',display:'flex',justifyContent:'center' }}>",
"        <div style={{ background:pg,padding:'3px 10px',borderRadius:'2px',boxShadow:'inset 0 1px 3px rgba(0,0,0,0.5),0 1px 4px rgba(0,0,0,0.6)',border:'1px solid rgba(0,0,0,0.4)',maxWidth:'90%' }}>",
"          <span style={{ fontSize:'0.58rem',fontWeight:900,color:pt,letterSpacing:'0.13em',textTransform:'uppercase',fontFamily:'Georgia,serif',textShadow:'0 1px 0 rgba(255,255,255,0.2)',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis',display:'block',maxWidth:'130px' }}>{dn}</span>",
"        </div>",
"      </div>",
"    </div>",
"  );",
"});",
"LockerSlot.displayName='LockerSlot';",
"",
"const ParquetStrip = () => (",
"  <div style={{ height:'36px',background:['repeating-linear-gradient(90deg,rgba(255,255,255,0.035) 0px,rgba(255,255,255,0.035) 1px,transparent 1px,transparent 60px)','repeating-linear-gradient(0deg,rgba(0,0,0,0.12) 0px,rgba(0,0,0,0.12) 1px,transparent 1px,transparent 18px)','linear-gradient(180deg,#3a1e08 0%,#241008 50%,#160a04 100%)'].join(','),boxShadow:'inset 0 5px 18px rgba(0,0,0,0.85)' }}/>",
");",
"",
"export default function Home() {",
"  const [slug, setSlug] = useState('');",
"  const [cards, setCards] = useState<any[]>([]);",
"  const [hof, setHof] = useState<string[]>([]);",
"  const [flippedSlug, setFlippedSlug] = useState<string|null>(null);",
"  const [loading, setLoading] = useState(false);",
"  const [error, setError] = useState('');",
"  const [sport, setSport] = useState('all');",
"  const [sort, setSort] = useState('default');",
"  const [mode, setMode] = useState<'locker'|'gallery'>('locker');",
"  const [lockerStart, setLockerStart] = useState(0);",
"",
"  useEffect(() => {",
"    const saved = localStorage.getItem('mynftlocker_hof')||localStorage.getItem('myNFTlocker_hof');",
"    if (saved) { setHof(JSON.parse(saved)); localStorage.setItem('mynftlocker_hof',saved); }",
"  }, []);",
"",
"  const handleStar = useCallback((s: string) => {",
"    setHof(prev => { const next = prev.includes(s)?prev.filter(x=>x!==s):[...prev,s]; localStorage.setItem('mynftlocker_hof',JSON.stringify(next)); return next; });",
"  }, []);",
"  const handleFlip = useCallback((s: string) => { setFlippedSlug(f=>f===s?null:s); }, []);",
"  const handlePrev = useCallback(() => { setLockerStart(s=>Math.max(0,s-5)); setFlippedSlug(null); }, []);",
"  const handleNext = useCallback((total: number) => { setLockerStart(s=>Math.min(s+5,total-1)); setFlippedSlug(null); }, []);",
"",
"  const fetchCards = async () => {",
"    if (!slug) return;",
"    setLoading(true); setError(''); setFlippedSlug(null); setLockerStart(0);",
"    try {",
"      const res = await fetch('/api/cards?slug='+slug);",
"      const data = await res.json();",
"      if (!data.cards) { setError('Joueur introuvable'); return; }",
"      setCards(data.cards);",
"    } catch { setError('Erreur reseau'); } finally { setLoading(false); }",
"  };",
"",
"  const filtered = cards",
"    .filter(c=>sport==='nba'?isNBA(c.slug):sport==='foot'?!isNBA(c.slug):true)",
"    .sort((a,b)=>{ if(sort==='rarity') return (RARITY_ORDER[a.rarityTyped]??9)-(RARITY_ORDER[b.rarityTyped]??9); if(sort==='name') return a.name.localeCompare(b.name); return 0; });",
"  const hofCards = filtered.filter(c=>hof.includes(c.slug));",
"  const mainCards = filtered.filter(c=>!hof.includes(c.slug));",
"",
"  const fBtn = (a: boolean): React.CSSProperties => ({ padding:'0.3rem 0.9rem',borderRadius:'999px',border:'1px solid',borderColor:a?'#c9a227':'#2a1506',background:a?'#c9a22720':'transparent',color:a?'#e8c456':'#6a4020',cursor:'pointer',fontSize:'0.75rem' });",
"  const gridHof:  React.CSSProperties = { display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(155px,1fr))',gap:'10px',background:'#2a1f00',padding:'10px' };",
"  const gridMain: React.CSSProperties = { display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(155px,1fr))',gap:'10px',background:'#120804',padding:'10px' };",
"  const pageBg = ['radial-gradient(ellipse 100% 30% at 50% 0%,rgba(60,30,5,0.8),transparent)','repeating-linear-gradient(92deg,transparent 0px,transparent 80px,rgba(0,0,0,0.07) 80px,rgba(0,0,0,0.07) 81px)','linear-gradient(180deg,#0e0604 0%,#080402 100%)'].join(',');",
"",
"  return (",
"    <main style={{ minHeight:'100vh',background:pageBg,color:'white',fontFamily:'system-ui,sans-serif' }}>",
"      {/* HEADER */}",
"      <div style={{ padding:'1.2rem 2rem 0.8rem',textAlign:'center' }}>",
"        <h1 style={{ fontSize:'2.2rem',fontWeight:900,margin:0,background:'linear-gradient(90deg,#c9a227,#f5d76e,#c9a227)',WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent',letterSpacing:'0.1em' }}>myNFTlocker</h1>",
"        <p style={{ margin:'3px 0 0',fontSize:'0.7rem',color:'#6a4020',letterSpacing:'0.25em',textTransform:'uppercase' }}>Ta collection NFT</p>",
"      </div>",
"",
"      {/* SEARCH */}",
"      <div style={{ display:'flex',gap:'0.5rem',maxWidth:'400px',margin:'0 auto 1rem',padding:'0 1rem' }}>",
"        <input style={{ flex:1,background:'#1a0a04',color:'#e8d5b0',padding:'0.55rem 1rem',borderRadius:'0.4rem',border:'1px solid #2a1506',outline:'none',fontSize:'0.9rem' }} placeholder='ton-slug-sorare' value={slug} onChange={e=>setSlug(e.target.value)} onKeyDown={e=>e.key==='Enter'&&fetchCards()} />",
"        <button style={{ background:'linear-gradient(135deg,#7c3aed,#5b21b6)',color:'white',padding:'0.55rem 1.3rem',borderRadius:'0.4rem',border:'none',cursor:'pointer',fontWeight:700 }} onClick={fetchCards}>{loading?'...':'Voir'}</button>",
"      </div>",
"      {error&&<p style={{ color:'#f87171',textAlign:'center' }}>{error}</p>}",
"",
"      {cards.length > 0 && (",
"        <div style={{ padding:'0 0 2rem' }}>",
"          {/* TOGGLE MODE */}",
"          <div style={{ display:'flex',justifyContent:'center',gap:'0.5rem',marginBottom:'0.8rem' }}>",
"            <button style={{ padding:'0.4rem 1.4rem',borderRadius:'999px',border:'1px solid',borderColor:mode==='locker'?'#c9a227':'#2a1506',background:mode==='locker'?'linear-gradient(135deg,#c9a227,#8b6500)':'transparent',color:mode==='locker'?'#0a0600':'#6a4020',cursor:'pointer',fontWeight:700,fontSize:'0.8rem',letterSpacing:'0.05em' }} onClick={()=>setMode('locker')}>\uD83C\uDFAE Vestiaire</button>",
"            <button style={{ padding:'0.4rem 1.4rem',borderRadius:'999px',border:'1px solid',borderColor:mode==='gallery'?'#c9a227':'#2a1506',background:mode==='gallery'?'linear-gradient(135deg,#c9a227,#8b6500)':'transparent',color:mode==='gallery'?'#0a0600':'#6a4020',cursor:'pointer',fontWeight:700,fontSize:'0.8rem',letterSpacing:'0.05em' }} onClick={()=>setMode('gallery')}>\uD83D\uDCE6 Galerie</button>",
"          </div>",
"",
"          {/* FILTRES */}",
"          <div style={{ display:'flex',gap:'0.4rem',justifyContent:'center',marginBottom:'0.6rem',flexWrap:'wrap' }}>",
"            {(['all','nba','foot'] as const).map(v=>(<button key={v} style={fBtn(sport===v)} onClick={()=>setSport(v)}>{v==='all'?'Tout':v==='nba'?'NBA':'Football'}</button>))}",
"            <span style={{ color:'#2a1506',padding:'0 0.2rem' }}>|</span>",
"            {(['default','rarity','name'] as const).map(v=>(<button key={v} style={fBtn(sort===v)} onClick={()=>setSort(v)}>{v==='default'?'Ordre':v==='rarity'?'Rarete':'Nom'}</button>))}",
"          </div>",
"          <p style={{ textAlign:'center',color:'#4a2a10',fontSize:'0.75rem',marginBottom:'1rem' }}>{filtered.length} cartes \u2022 {hofCards.length} en Hall of Fame</p>",
"",
"          {/* MODE VESTIAIRE */}",
"          {mode==='locker' && (",
"            <div style={{ maxWidth:'1320px',margin:'0 auto' }}>",
"              <LockerRoomScene",
"                cards={filtered}",
"                startIndex={lockerStart}",
"                hof={hof}",
"                flippedSlug={flippedSlug}",
"                onFlip={handleFlip}",
"                onStar={handleStar}",
"                onPrev={handlePrev}",
"                onNext={()=>handleNext(filtered.length)}",
"                total={filtered.length}",
"              />",
"            </div>",
"          )}",
"",
"          {/* MODE GALERIE */}",
"          {mode==='gallery' && (",
"            <div style={{ padding:'0 1rem' }}>",
"              {hofCards.length>0&&(",
"                <div style={{ maxWidth:'1320px',margin:'0 auto 2.5rem' }}>",
"                  <div style={{ textAlign:'center',marginBottom:'0.8rem' }}>",
"                    <h2 style={{ margin:0,fontSize:'1rem',fontWeight:900,color:'#c9a227',letterSpacing:'0.25em',textTransform:'uppercase',textShadow:'0 0 20px rgba(201,162,39,0.4)' }}>\uD83C\uDFC6 HALL OF FAME</h2>",
"                    <div style={{ margin:'4px auto 0',width:'80px',height:'1px',background:'linear-gradient(90deg,transparent,#c9a227,transparent)' }}/>",
"                  </div>",
"                  <div style={{ background:'radial-gradient(ellipse at 50% 0%,#1a1400,#080600)',border:'1px solid #3a2800',borderRadius:'4px',overflow:'hidden',boxShadow:'0 0 30px rgba(0,0,0,0.9)' }}>",
"                    <div style={gridHof}>{hofCards.map(c=><LockerSlot key={c.slug} card={c} isFlipped={flippedSlug===c.slug} isStarred={true} isHof={true} onFlip={handleFlip} onStar={handleStar}/>)}</div>",
"                    <ParquetStrip/>",
"                  </div>",
"                </div>",
"              )}",
"              <div style={{ maxWidth:'1320px',margin:'0 auto' }}>",
"                {hofCards.length>0&&<h2 style={{ margin:'0 0 0.8rem',fontSize:'0.85rem',fontWeight:700,color:'#5a3010',letterSpacing:'0.25em',textTransform:'uppercase',textAlign:'center' }}>\uD83D\uDCE6 COLLECTION</h2>}",
"                <div style={{ background:'#0a0502',border:'1px solid #180a03',borderRadius:'4px',overflow:'hidden' }}>",
"                  <div style={gridMain}>{mainCards.map(c=><LockerSlot key={c.slug} card={c} isFlipped={flippedSlug===c.slug} isStarred={false} isHof={false} onFlip={handleFlip} onStar={handleStar}/>)}</div>",
"                  <ParquetStrip/>",
"                </div>",
"              </div>",
"            </div>",
"          )}",
"        </div>",
"      )}",
"    </main>",
"  );",
"}",
].join('\n');

fs.writeFileSync('app/page.tsx', page);
console.log('OK - page.tsx mis a jour avec toggle Vestiaire/Galerie.');
