const fs = require('fs');

const route = [
"import { NextRequest, NextResponse } from 'next/server';",
"",
"export async function GET(request: NextRequest) {",
"  const { searchParams } = new URL(request.url);",
"  const slug = searchParams.get('slug');",
"  if (!slug) return NextResponse.json({ error: 'Slug manquant' }, { status: 400 });",
"  const allCards: any[] = [];",
"  let cursor: string | null = null;",
"  let page = 0;",
"  while (page < 500) {",
"    const after = cursor ? `, after: \"${cursor}\"` : '';",
"    const query = `query {",
"      user(slug: \"${slug}\") {",
"        cards(first: 30${after}) {",
"          nodes {",
"            slug name rarityTyped pictureUrl",
"            ... on NBACard {",
"              anyPlayer { lastName shirtNumber }",
"            }",
"          }",
"          pageInfo { hasNextPage endCursor }",
"        }",
"      }",
"    }`;",
"    const res = await fetch('https://api.sorare.com/federation/graphql', {",
"      method: 'POST',",
"      headers: { 'Content-Type': 'application/json' },",
"      body: JSON.stringify({ query }),",
"    });",
"    const data = await res.json();",
"    if (data.errors) { console.error('GraphQL error:', JSON.stringify(data.errors)); break; }",
"    const cards = data?.data?.user?.cards;",
"    if (!cards) break;",
"    allCards.push(...cards.nodes);",
"    console.log(`Page ${page + 1}: ${allCards.length} cartes`);",
"    if (!cards.pageInfo.hasNextPage) break;",
"    cursor = cards.pageInfo.endCursor;",
"    page++;",
"  }",
"  return NextResponse.json({ cards: allCards, total: allCards.length });",
"}",
].join('\n');

fs.writeFileSync('app/api/cards/route.ts', route);
console.log('OK - route.ts corrige.');
